define("frontend-js-metal-web@1.0.7/metal/src/core",["exports"],function(g){Object.defineProperty(g,"__esModule",{value:!0});var e="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol?"symbol":typeof b},f=function(){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");}b.abstractMethod=function(){throw Error("Unimplemented abstract method");};b.collectSuperClassesProperty=
function(a,c){for(var d=[a[c]];a.__proto__&&!a.__proto__.isPrototypeOf(Function);)a=a.__proto__,d.push(a[c]);return d};b.getFunctionName=function(a){if(!a.name){var c=a.toString();a.name=c.substring(9,c.indexOf("("))}return a.name};b.getUid=function(a){return a?a[b.UID_PROPERTY]||(a[b.UID_PROPERTY]=b.uniqueIdCounter_++):b.uniqueIdCounter_++};b.identityFunction=function(a){return a};b.isBoolean=function(a){return"boolean"===typeof a};b.isDef=function(a){return void 0!==a};b.isDefAndNotNull=function(a){return b.isDef(a)&&
!b.isNull(a)};b.isDocument=function(a){return a&&"object"===("undefined"===typeof a?"undefined":e(a))&&9===a.nodeType};b.isElement=function(a){return a&&"object"===("undefined"===typeof a?"undefined":e(a))&&1===a.nodeType};b.isFunction=function(a){return"function"===typeof a};b.isNull=function(a){return null===a};b.isNumber=function(a){return"number"===typeof a};b.isWindow=function(a){return null!==a&&a===a.window};b.isObject=function(a){var c="undefined"===typeof a?"undefined":e(a);return"object"===
c&&null!==a||"function"===c};b.isPromise=function(a){return a&&"object"===("undefined"===typeof a?"undefined":e(a))&&"function"===typeof a.then};b.isString=function(a){return"string"===typeof a};b.mergeSuperClassesProperty=function(a,c,d){var h=c+"_MERGED";if(a.hasOwnProperty(h))return!1;c=b.collectSuperClassesProperty(a,c);d&&(c=d(c));a[h]=c;return!0};b.nullFunction=function(){};return b}();f.UID_PROPERTY="core_"+(1E9*Math.random()>>>0);f.uniqueIdCounter_=1;g.default=f});
define("frontend-js-metal-web@1.0.7/metal/src/array/array",["exports","../core"],function(g,f){Object.defineProperty(g,"__esModule",{value:!0});var h=f&&f.__esModule?f:{default:f},k=function(){function e(){if(!(this instanceof e))throw new TypeError("Cannot call a class as a function");}e.equal=function(a,b){if(a.length!==b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0};e.firstDefinedValue=function(a){for(var b=0;b<a.length;b++)if(void 0!==a[b])return a[b]};e.flatten=
function(a,b){for(var c=b||[],d=0;d<a.length;d++)Array.isArray(a[d])?e.flatten(a[d],c):c.push(a[d]);return c};e.remove=function(a,b){var c=a.indexOf(b),d;(d=0<=c)&&e.removeAt(a,c);return d};e.removeAt=function(a,b){return 1===Array.prototype.splice.call(a,b,1).length};e.slice=function(a,b,c){var d=[];for(c=h.default.isDef(c)?c:a.length;b<c;b++)d.push(a[b]);return d};return e}();g.default=k});
define("frontend-js-metal-web@1.0.7/metal/src/async/async",["exports"],function(h){Object.defineProperty(h,"__esModule",{value:!0});var a={throwException:function(b){a.nextTick(function(){throw b;})},run:function(b,e){a.run.workQueueScheduled_||(a.nextTick(a.run.processWorkQueue),a.run.workQueueScheduled_=!0);a.run.workQueue_.push(new a.run.WorkItem_(b,e))}};a.run.workQueueScheduled_=!1;a.run.workQueue_=[];a.run.processWorkQueue=function(){for(;a.run.workQueue_.length;){var b=a.run.workQueue_;a.run.workQueue_=
[];for(var e=0;e<b.length;e++){var d=b[e];try{d.fn.call(d.scope)}catch(g){a.throwException(g)}}}a.run.workQueueScheduled_=!1};a.run.WorkItem_=function(b,e){this.fn=b;this.scope=e};a.nextTick=function(b,e){var d=b;e&&(d=b.bind(e));d=a.nextTick.wrapCallback_(d);"function"===typeof setImmediate?setImmediate(d):(a.nextTick.setImmediate_||(a.nextTick.setImmediate_=a.nextTick.getSetImmediateEmulator_()),a.nextTick.setImmediate_(d))};a.nextTick.setImmediate_=null;a.nextTick.getSetImmediateEmulator_=function(){var b;
"function"===typeof MessageChannel&&(b=MessageChannel);"undefined"===typeof b&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(b=function(){var c=document.createElement("iframe");c.style.display="none";c.src="";document.documentElement.appendChild(c);var f=c.contentWindow,c=f.document;c.open();c.write("");c.close();var k="callImmediate"+Math.random(),l=f.location.protocol+"//"+f.location.host,c=function(m){if(m.origin===l||m.data===k)this.port1.onmessage()}.bind(this);f.addEventListener("message",
c,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(k,l)}}});if("undefined"!==typeof b){var e=new b,d={},g=d;e.port1.onmessage=function(){d=d.next;var c=d.cb;d.cb=null;c()};return function(c){g.next={cb:c};g=g.next;e.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(c){var f=document.createElement("script");f.onreadystatechange=function(){f.onreadystatechange=null;f.parentNode.removeChild(f);f=null;c();c=null};
document.documentElement.appendChild(f)}:function(c){setTimeout(c,0)}};a.nextTick.wrapCallback_=function(b){return b};h.default=a});
define("frontend-js-metal-web@1.0.7/metal/src/disposable/Disposable",["exports"],function(b){Object.defineProperty(b,"__esModule",{value:!0});var c=function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");this.disposed_=!1}a.prototype.dispose=function(){this.disposed_||(this.disposeInternal(),this.disposed_=!0)};a.prototype.disposeInternal=function(){};a.prototype.isDisposed=function(){return this.disposed_};return a}();b.default=c});
define("frontend-js-metal-web@1.0.7/metal/src/object/object",["exports"],function(g){Object.defineProperty(g,"__esModule",{value:!0});var h=function(){function f(){if(!(this instanceof f))throw new TypeError("Cannot call a class as a function");}f.mixin=function(c){for(var d,b,a=1;a<arguments.length;a++)for(d in b=arguments[a],b)c[d]=b[d];return c};f.getObjectByName=function(c,d){var b=d||window;return c.split(".").reduce(function(a,e){return a[e]},b)};f.map=function(c,d){for(var b={},a=Object.keys(c),
e=0;e<a.length;e++)b[a[e]]=d(a[e],c[a[e]]);return b};f.shallowEqual=function(c,d){if(c===d)return!0;var b=Object.keys(c),a=Object.keys(d);if(b.length!==a.length)return!1;for(a=0;a<b.length;a++)if(c[b[a]]!==d[b[a]])return!1;return!0};return f}();g.default=h});
define("frontend-js-metal-web@1.0.7/metal/src/string/string",["exports"],function(f){Object.defineProperty(f,"__esModule",{value:!0});var g=function(){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");}b.collapseBreakingSpaces=function(a){return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};b.escapeRegex=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};b.getRandomString=function(){return Math.floor(2147483648*
Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36)};b.hashCode=function(a){for(var c=0,d=0,e=a.length;d<e;d++)c=31*c+a.charCodeAt(d),c%=4294967296;return c};b.replaceInterval=function(a,c,d,e){return a.substring(0,c)+e+a.substring(d)};return b}();f.default=g});
define("frontend-js-metal-web@1.0.7/metal/src/metal","exports ./core ./array/array ./async/async ./disposable/Disposable ./object/object ./string/string".split(" "),function(a,c,e,f,g,h,k){function b(d){return d&&d.__esModule?d:{default:d}}Object.defineProperty(a,"__esModule",{value:!0});a.string=a.object=a.Disposable=a.async=a.array=a.core=void 0;c=b(c);e=b(e);f=b(f);g=b(g);h=b(h);k=b(k);a.default=c.default;a.core=c.default;a.array=e.default;a.async=f.default;a.Disposable=g.default;a.object=h.default;
a.string=k.default});
define("frontend-js-metal-web@1.0.7/metal-events/src/EventHandle",["exports","metal/src/metal"],function(d,e){function f(c,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);c.prototype=Object.create(a&&a.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(c,a):c.__proto__=a)}Object.defineProperty(d,"__esModule",{value:!0});var l=function(c){function a(g,
h,k){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");var b;b=c.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");b=!b||"object"!==typeof b&&"function"!==typeof b?this:b;b.emitter_=g;b.event_=h;b.listener_=k;return b}f(a,c);a.prototype.disposeInternal=function(){this.removeListener();this.listener_=this.emitter_=null};a.prototype.removeListener=function(){this.emitter_.isDisposed()||this.emitter_.removeListener(this.event_,
this.listener_)};return a}(e.Disposable);d.default=l});
define("frontend-js-metal-web@1.0.7/metal-events/src/EventEmitter",["exports","metal/src/metal","./EventHandle"],function(m,l,k){function p(g,c){if("function"!==typeof c&&null!==c)throw new TypeError("Super expression must either be null or a function, not "+typeof c);g.prototype=Object.create(c&&c.prototype,{constructor:{value:g,enumerable:!1,writable:!0,configurable:!0}});c&&(Object.setPrototypeOf?Object.setPrototypeOf(g,c):g.__proto__=c)}Object.defineProperty(m,"__esModule",{value:!0});var n=k&&
k.__esModule?k:{default:k};k=function(g){function c(){if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");var a;a=g.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!a||"object"!==typeof a&&"function"!==typeof a?this:a;a.events_=[];a.maxListeners_=10;a.shouldUseFacade_=!1;return a}p(c,g);c.prototype.addListener=function(a,b,d){this.validateListener_(b);a=this.normalizeEvents_(a);for(var e=0;e<a.length;e++)this.addSingleListener_(a[e],
b,d);return new n.default(this,a,b)};c.prototype.addSingleListener_=function(a,b,d,e){this.emit("newListener",a,b);this.events_[a]||(this.events_[a]=[]);this.events_[a].push({default:d,fn:b,origin:e});b=this.events_[a];b.length>this.maxListeners_&&!b.warned&&(console.warn("Possible EventEmitter memory leak detected. %d listeners added for event %s. Use emitter.setMaxListeners() to increase limit.",b.length,a),b.warned=!0)};c.prototype.disposeInternal=function(){this.events_=[]};c.prototype.emit=function(a){var b=
l.array.slice(arguments,1),d=(this.events_[a]||[]).concat(),e;this.getShouldUseFacade()&&(e={preventDefault:function(){e.preventedDefault=!0},target:this,type:a},b.push(e));for(var h=[],f=0;f<d.length;f++)d[f].default?h.push(d[f]):d[f].fn.apply(this,b);if(!e||!e.preventedDefault)for(f=0;f<h.length;f++)h[f].fn.apply(this,b);"*"!==a&&this.emit.apply(this,["*",a].concat(b));return 0<d.length};c.prototype.getShouldUseFacade=function(){return this.shouldUseFacade_};c.prototype.listeners=function(a){return(this.events_[a]||
[]).map(function(b){return b.fn})};c.prototype.many=function(a,b,d){a=this.normalizeEvents_(a);for(var e=0;e<a.length;e++)this.many_(a[e],b,d);return new n.default(this,a,d)};c.prototype.many_=function(a,b,d){function e(){0===--b&&h.removeListener(a,e);d.apply(h,arguments)}var h=this;0>=b||h.addSingleListener_(a,e,!1,d)};c.prototype.matchesListener_=function(a,b){return a.fn===b||a.origin&&a.origin===b};c.prototype.normalizeEvents_=function(a){return l.core.isString(a)?[a]:a};c.prototype.off=function(a,
b){this.validateListener_(b);a=this.normalizeEvents_(a);for(var d=0;d<a.length;d++)this.removeMatchingListenerObjs_(this.events_[a[d]]||[],b);return this};c.prototype.on=function(){return this.addListener.apply(this,arguments)};c.prototype.once=function(a,b){return this.many(a,1,b)};c.prototype.removeAllListeners=function(a){if(a){a=this.normalizeEvents_(a);for(var b=0;b<a.length;b++)this.events_[a[b]]=null}else this.events_={};return this};c.prototype.removeMatchingListenerObjs_=function(a,b){for(var d=
a.length-1;0<=d;d--)this.matchesListener_(a[d],b)&&a.splice(d,1)};c.prototype.removeListener=function(){return this.off.apply(this,arguments)};c.prototype.setMaxListeners=function(a){this.maxListeners_=a;return this};c.prototype.setShouldUseFacade=function(a){this.shouldUseFacade_=a;return this};c.prototype.validateListener_=function(a){if(!l.core.isFunction(a))throw new TypeError("Listener must be a function");};return c}(l.Disposable);m.default=k});
define("frontend-js-metal-web@1.0.7/metal-events/src/EventEmitterProxy",["exports","metal/src/metal"],function(h,k){function l(e,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);e.prototype=Object.create(b&&b.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(e,b):e.__proto__=b)}Object.defineProperty(h,"__esModule",{value:!0});var m=function(e){function b(a,
d,f,g){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var c;c=e.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");c=!c||"object"!==typeof c&&"function"!==typeof c?this:c;c.blacklist_=f||{};c.originEmitter_=a;c.pendingEvents_=[];c.proxiedEvents_={};c.targetEmitter_=d;c.whitelist_=g;c.startProxy_();return c}l(b,e);b.prototype.addListener_=function(a,d){return this.originEmitter_.on(a,d)};b.prototype.addListenerForEvent_=
function(a){return this.addListener_(a,this.emitOnTarget_.bind(this,a))};b.prototype.disposeInternal=function(){this.removeListeners_();this.targetEmitter_=this.originEmitter_=this.proxiedEvents_=null};b.prototype.emitOnTarget_=function(a){var d=[a].concat(k.array.slice(arguments,1));this.targetEmitter_.emit.apply(this.targetEmitter_,d)};b.prototype.proxyEvent=function(a){this.shouldProxyEvent_(a)&&this.tryToAddListener_(a)};b.prototype.removeListeners_=function(){for(var a=Object.keys(this.proxiedEvents_),
d=0;d<a.length;d++)this.proxiedEvents_[a[d]].removeListener();this.proxiedEvents_={};this.pendingEvents_=[]};b.prototype.setOriginEmitter=function(a){var d=this,f=this.originEmitter_?Object.keys(this.proxiedEvents_):this.pendingEvents_;this.removeListeners_();this.originEmitter_=a;f.forEach(function(g){return d.proxyEvent(g)})};b.prototype.shouldProxyEvent_=function(a){return this.whitelist_&&!this.whitelist_[a]||this.blacklist_[a]?!1:!this.proxiedEvents_[a]};b.prototype.startProxy_=function(){this.targetEmitter_.on("newListener",
this.proxyEvent.bind(this))};b.prototype.tryToAddListener_=function(a){this.originEmitter_?this.proxiedEvents_[a]=this.addListenerForEvent_(a):this.pendingEvents_.push(a)};return b}(k.Disposable);h.default=m});
define("frontend-js-metal-web@1.0.7/metal-events/src/EventHandler",["exports","metal/src/metal"],function(d,e){function f(c,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);c.prototype=Object.create(b&&b.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(c,b):c.__proto__=b)}Object.defineProperty(d,"__esModule",{value:!0});var g=function(c){function b(){if(!(this instanceof
b))throw new TypeError("Cannot call a class as a function");var a;a=c.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!a||"object"!==typeof a&&"function"!==typeof a?this:a;a.eventHandles_=[];return a}f(b,c);b.prototype.add=function(){for(var a=0;a<arguments.length;a++)this.eventHandles_.push(arguments[a])};b.prototype.disposeInternal=function(){this.eventHandles_=null};b.prototype.removeAllListeners=function(){for(var a=0;a<this.eventHandles_.length;a++)this.eventHandles_[a].removeListener();
this.eventHandles_=[]};return b}(e.Disposable);d.default=g});
define("frontend-js-metal-web@1.0.7/metal-events/src/events",["exports","./EventEmitter","./EventEmitterProxy","./EventHandle","./EventHandler"],function(a,b,e,f,g){function c(d){return d&&d.__esModule?d:{default:d}}Object.defineProperty(a,"__esModule",{value:!0});a.EventHandler=a.EventHandle=a.EventEmitterProxy=a.EventEmitter=void 0;b=c(b);e=c(e);f=c(f);g=c(g);a.default=b.default;a.EventEmitter=b.default;a.EventEmitterProxy=e.default;a.EventHandle=f.default;a.EventHandler=g.default});
define("frontend-js-metal-web@1.0.7/metal-dom/src/DomEventHandle",["exports","metal-events/src/events"],function(d,e){function f(c,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);c.prototype=Object.create(a&&a.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(c,a):c.__proto__=a)}Object.defineProperty(d,"__esModule",{value:!0});var l=function(c){function a(b,
g,h,k){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");b=c.call(this,b,g,h);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");b=!b||"object"!==typeof b&&"function"!==typeof b?this:b;b.capture_=k;return b}f(a,c);a.prototype.removeListener=function(){this.emitter_.removeEventListener(this.event_,this.listener_,this.capture_)};return a}(e.EventHandle);d.default=l});
define("frontend-js-metal-web@1.0.7/metal-dom/src/dom",["exports","metal/src/metal","./DomEventHandle"],function(m,g,h){Object.defineProperty(m,"__esModule",{value:!0});var n=h&&h.__esModule?h:{default:h};h=function(){function c(){if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");}c.addClasses=function(a,b){g.core.isObject(a)&&g.core.isString(b)&&("classList"in a?c.addClassesWithNative_(a,b):c.addClassesWithoutNative_(a,b))};c.addClassesWithNative_=function(a,b){b.split(" ").forEach(function(d){d&&
a.classList.add(d)})};c.addClassesWithoutNative_=function(a,b){var d=" "+a.className+" ",e="";b=b.split(" ");for(var f=0;f<b.length;f++){var k=b[f];-1===d.indexOf(" "+k+" ")&&(e+=" "+k)}e&&(a.className+=e)};c.closest=function(a,b){for(;a&&!c.match(a,b);)a=a.parentNode;return a};c.append=function(a,b){g.core.isString(b)&&(b=c.buildFragment(b));if(b instanceof NodeList)for(var d=Array.prototype.slice.call(b),e=0;e<d.length;e++)a.appendChild(d[e]);else a.appendChild(b);return b};c.buildFragment=function(a){var b=
document.createElement("div");b.innerHTML="\x3cbr\x3e"+a;b.removeChild(b.firstChild);for(a=document.createDocumentFragment();b.firstChild;)a.appendChild(b.firstChild);return a};c.contains=function(a,b){return g.core.isDocument(a)?a.documentElement.contains(b):a.contains(b)};c.delegate=function(a,b,d,e){var f=c.customEvents[b];f&&f.delegate&&(b=f.originalEvent,e=f.handler.bind(f,e));return c.on(a,b,c.handleDelegateEvent_.bind(null,d,e))};c.enterDocument=function(a){a&&c.append(document.body,a)};c.exitDocument=
function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};c.handleDelegateEvent_=function(a,b,d){c.normalizeDelegateEvent_(d);for(var e=d.target,f=!0;e&&!d.stopped;){g.core.isString(a)&&c.match(e,a)&&(d.delegateTarget=e,f&=b(d));if(e===d.currentTarget)break;e=e.parentNode}d.delegateTarget=null;return f};c.hasClass=function(a,b){return"classList"in a?c.hasClassWithNative_(a,b):c.hasClassWithoutNative_(a,b)};c.hasClassWithNative_=function(a,b){return a.classList.contains(b)};c.hasClassWithoutNative_=
function(a,b){return 0<=(" "+a.className+" ").indexOf(" "+b+" ")};c.isEmpty=function(a){return 0===a.childNodes.length};c.match=function(a,b){if(!a||1!==a.nodeType)return!1;var d=Element.prototype;return(d=d.matches||d.webkitMatchesSelector||d.mozMatchesSelector||d.msMatchesSelector||d.oMatchesSelector)?d.call(a,b):c.matchFallback_(a,b)};c.matchFallback_=function(a,b){for(var d=document.querySelectorAll(b,a.parentNode),e=0;e<d.length;++e)if(d[e]===a)return!0;return!1};c.next=function(a,b){do if((a=
a.nextSibling)&&c.match(a,b))return a;while(a);return null};c.normalizeDelegateEvent_=function(a){a.stopPropagation=c.stopPropagation_;a.stopImmediatePropagation=c.stopImmediatePropagation_};c.on=function(a,b,d,e){if(g.core.isString(a))return c.delegate(document,b,a,d);var f=c.customEvents[b];f&&f.event&&(b=f.originalEvent,d=f.handler.bind(f,d));a.addEventListener(b,d,e);return new n.default(a,b,d,e)};c.once=function(a,b,d){var e=this.on(a,b,function(){e.removeListener();return d.apply(this,arguments)});
return e};c.parent=function(a,b){return c.closest(a.parentNode,b)};c.registerCustomEvent=function(a,b){c.customEvents[a]=b};c.removeChildren=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};c.removeClasses=function(a,b){g.core.isObject(a)&&g.core.isString(b)&&("classList"in a?c.removeClassesWithNative_(a,b):c.removeClassesWithoutNative_(a,b))};c.removeClassesWithNative_=function(a,b){b.split(" ").forEach(function(d){d&&a.classList.remove(d)})};c.removeClassesWithoutNative_=function(a,b){var d=
" "+a.className+" ";b=b.split(" ");for(var e=0;e<b.length;e++)d=d.replace(" "+b[e]+" "," ");a.className=d.trim()};c.replace=function(a,b){a&&b&&a!==b&&a.parentNode&&(a.parentNode.insertBefore(b,a),a.parentNode.removeChild(a))};c.stopImmediatePropagation_=function(){this.stopped=!0;Event.prototype.stopImmediatePropagation.call(this)};c.stopPropagation_=function(){this.stopped=!0;Event.prototype.stopPropagation.call(this)};c.supportsEvent=function(a,b){if(c.customEvents[b])return!0;g.core.isString(a)&&
(l[a]||(l[a]=document.createElement(a)),a=l[a]);return"on"+b in a};c.toElement=function(a){return g.core.isElement(a)||g.core.isDocument(a)?a:g.core.isString(a)?"#"===a[0]&&-1===a.indexOf(" ")?document.getElementById(a.substr(1)):document.querySelector(a):null};c.toggleClasses=function(a,b){g.core.isObject(a)&&g.core.isString(b)&&("classList"in a?c.toggleClassesWithNative_(a,b):c.toggleClassesWithoutNative_(a,b))};c.toggleClassesWithNative_=function(a,b){b.split(" ").forEach(function(d){a.classList.toggle(d)})};
c.toggleClassesWithoutNative_=function(a,b){var d=" "+a.className+" ";b=b.split(" ");for(var e=0;e<b.length;e++)var f=" "+b[e]+" ",k=d.indexOf(f),d=-1===k?d+b[e]+" ":d.substring(0,k)+" "+d.substring(k+f.length);a.className=d.trim()};c.triggerEvent=function(a,b,d){var e=document.createEvent("HTMLEvents");e.initEvent(b,!0,!0);g.object.mixin(e,d);a.dispatchEvent(e)};return c}();var l={};h.customEvents={};m.default=h});
define("frontend-js-metal-web@1.0.7/metal-dom/src/DomEventEmitterProxy",["exports","./dom","metal-events/src/events"],function(h,d,k){function l(c,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);c.prototype=Object.create(b&&b.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(c,b):c.__proto__=b)}Object.defineProperty(h,"__esModule",{value:!0});var f=
d&&d.__esModule?d:{default:d};d=function(c){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var a=c.apply(this,arguments);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!a||"object"!==typeof a&&"function"!==typeof a?this:a}l(b,c);b.prototype.addListener_=function(a,g){if(this.originEmitter_.addEventListener){if(this.isDelegateEvent_(a)){var e=a.indexOf(":",9),m=a.substring(9,e),e=a.substring(e+1);return f.default.delegate(this.originEmitter_,
m,e,g)}return f.default.on(this.originEmitter_,a,g)}return c.prototype.addListener_.call(this,a,g)};b.prototype.isDelegateEvent_=function(a){return"delegate:"===a.substr(0,9)};b.prototype.isSupportedDomEvent_=function(a){return this.originEmitter_&&this.originEmitter_.addEventListener?this.isDelegateEvent_(a)&&-1!==a.indexOf(":",9)||f.default.supportsEvent(this.originEmitter_,a):!0};b.prototype.shouldProxyEvent_=function(a){return c.prototype.shouldProxyEvent_.call(this,a)&&this.isSupportedDomEvent_(a)};
return b}(k.EventEmitterProxy);h.default=d});
define("frontend-js-metal-web@1.0.7/metal-dom/src/features",["exports","./dom","metal/src/metal"],function(g,b,h){Object.defineProperty(g,"__esModule",{value:!0});var k=b&&b.__esModule?b:{default:b};b=function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");}a.checkAnimationEventName=function(){void 0===a.animationEventName_&&(a.animationEventName_={animation:a.checkAnimationEventName_("animation"),transition:a.checkAnimationEventName_("transition")});
return a.animationEventName_};a.checkAnimationEventName_=function(c){for(var f=["Webkit","MS","O",""],e=h.string.replaceInterval(c,0,1,c.substring(0,1).toUpperCase()),l=[e+"End",e+"End",e+"End",c+"end"],d=0;d<f.length;d++)if(void 0!==a.animationElement_.style[f[d]+e])return f[d].toLowerCase()+l[d];return c+"end"};a.checkAttrOrderChange=function(){if(void 0===a.attrOrderChange_){var c=document.createElement("div");k.default.append(c,'\x3cdiv data-component\x3d"" data-ref\x3d""\x3e\x3c/div\x3e');a.attrOrderChange_=
'\x3cdiv data-component\x3d"" data-ref\x3d""\x3e\x3c/div\x3e'!==c.innerHTML}return a.attrOrderChange_};return a}();b.animationElement_=document.createElement("div");b.animationEventName_=void 0;b.attrOrderChange_=void 0;g.default=b});
define("frontend-js-metal-web@1.0.7/metal-dom/src/globalEval",["exports","metal/src/metal","./dom"],function(k,h,f){Object.defineProperty(k,"__esModule",{value:!0});var g=f&&f.__esModule?f:{default:f};f=function(){function e(){if(!(this instanceof e))throw new TypeError("Cannot call a class as a function");}e.run=function(a,b){var c=document.createElement("script");c.text=a;b?b(c):document.head.appendChild(c);g.default.exitDocument(c);return c};e.runFile=function(a,b,c){var d=document.createElement("script");
d.src=a;a=function(){g.default.exitDocument(d);b&&b()};g.default.once(d,"load",a);g.default.once(d,"error",a);c?c(d):document.head.appendChild(d);return d};e.runScript=function(a,b,c){var d=function(){b&&b()};if(a.type&&"text/javascript"!==a.type)h.async.nextTick(d);else{g.default.exitDocument(a);if(a.src)return e.runFile(a.src,b,c);h.async.nextTick(d);return e.run(a.text,c)}};e.runScriptsInElement=function(a,b,c){a=a.querySelectorAll("script");a.length?e.runScriptsInOrder(a,0,b,c):b&&h.async.nextTick(b)};
e.runScriptsInOrder=function(a,b,c,d){e.runScript(a.item(b),function(){b<a.length-1?e.runScriptsInOrder(a,b+1,c,d):c&&h.async.nextTick(c)},d)};return e}();k.default=f});
define("frontend-js-metal-web@1.0.7/metal-dom/src/globalEvalStyles",["exports","metal/src/metal","./dom"],function(k,g,f){Object.defineProperty(k,"__esModule",{value:!0});var l=f&&f.__esModule?f:{default:f};f=function(){function e(){if(!(this instanceof e))throw new TypeError("Cannot call a class as a function");}e.run=function(a,c){var d=document.createElement("style");d.innerHTML=a;c?c(d):document.head.appendChild(d);return d};e.runFile=function(a,c,d){var b=document.createElement("link");b.rel=
"stylesheet";b.href=a;e.runStyle(b,c,d);return b};e.runStyle=function(a,c,d){var b=function(){c&&c()};if(a.rel&&"stylesheet"!==a.rel)g.async.nextTick(b);else return"STYLE"===a.tagName?g.async.nextTick(b):(l.default.once(a,"load",b),l.default.once(a,"error",b)),d?d(a):document.head.appendChild(a),a};e.runStylesInElement=function(a,c,d){var b=a.querySelectorAll("style,link");if(0===b.length&&c)g.async.nextTick(c);else{var m=0;a=function(){c&&++m===b.length&&g.async.nextTick(c)};for(var h=0;h<b.length;h++)e.runStyle(b[h],
a,d)}};return e}();k.default=f});
define("frontend-js-metal-web@1.0.7/metal-dom/src/events",["./dom","./features"],function(d,e){var g=d&&d.__esModule?d:{default:d},m=e&&e.__esModule?e:{default:e},h={mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"};Object.keys(h).forEach(function(a){g.default.registerCustomEvent(a,{delegate:!0,handler:function(f,b){var c=b.relatedTarget,k=b.delegateTarget;if(!c||c!==k&&!k.contains(c))return b.customType=a,f(b)},originalEvent:h[a]})});var l={animation:"animationend",
transition:"transitionend"};Object.keys(l).forEach(function(a){var f=l[a];g.default.registerCustomEvent(f,{event:!0,delegate:!0,handler:function(b,c){c.customType=f;return b(c)},originalEvent:m.default.checkAnimationEventName()[a]})})});
define("frontend-js-metal-web@1.0.7/metal-dom/src/all/dom","exports ../dom ../DomEventEmitterProxy ../DomEventHandle ../features ../globalEval ../globalEvalStyles ../events".split(" "),function(a,c,e,f,g,h,k){function b(d){return d&&d.__esModule?d:{default:d}}Object.defineProperty(a,"__esModule",{value:!0});a.globalEvalStyles=a.globalEval=a.features=a.DomEventHandle=a.DomEventEmitterProxy=a.dom=void 0;c=b(c);e=b(e);f=b(f);g=b(g);h=b(h);k=b(k);a.default=c.default;a.dom=c.default;a.DomEventEmitterProxy=
e.default;a.DomEventHandle=f.default;a.features=g.default;a.globalEval=h.default;a.globalEvalStyles=k.default});
define("frontend-js-metal-web@1.0.7/metal-promise/src/promise/Promise",["exports","metal/src/metal"],function(r,m){function u(k,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);k.prototype=Object.create(a&&a.prototype,{constructor:{value:k,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(k,a):k.__proto__=a)}Object.defineProperty(r,"__esModule",{value:!0});r.CancellablePromise=
void 0;var q=function(){};q.prototype.then=function(){};q.IMPLEMENTED_BY_PROP="$goog_Thenable";q.addImplementation=function(k){k.prototype.then=k.prototype.then;k.prototype.$goog_Thenable=!0};q.isImplementedBy=function(k){if(!k)return!1;try{return!!k.$goog_Thenable}catch(a){return!1}};var t=function(k){var a=Array.prototype.slice.call(arguments,1);return function(){var c=a.slice();c.push.apply(c,arguments);return k.apply(this,c)}},b=function a(c,e){this.state_=a.State_.PENDING;this.result_=void 0;
this.callbackEntries_=this.parent_=null;this.executing_=!1;0<a.UNHANDLED_REJECTION_DELAY?this.unhandledRejectionId_=0:0===a.UNHANDLED_REJECTION_DELAY&&(this.hadUnhandledRejection_=!1);try{var d=this;c.call(e,function(g){d.resolve_(a.State_.FULFILLED,g)},function(g){d.resolve_(a.State_.REJECTED,g)})}catch(f){this.resolve_(a.State_.REJECTED,f)}};b.UNHANDLED_REJECTION_DELAY=0;b.State_={PENDING:0,BLOCKED:1,FULFILLED:2,REJECTED:3};b.CallbackEntry_=null;b.resolve=function(a){return new b(function(c){c(a)})};
b.reject=function(a){return new b(function(c,e){e(a)})};b.race=function(a){return new b(function(c,e){a.length||c(void 0);for(var d=0,f;f=a[d];d++)f.then(c,e)})};b.all=function(a){return new b(function(c,e){var d=a.length,f=[];if(d)for(var g=function(p,s){d--;f[p]=s;0===d&&c(f)},l=function(p){e(p)},h=0,n;n=a[h];h++)n.then(t(g,h),l);else c(f)})};b.firstFulfilled=function(a){return new b(function(c,e){var d=a.length,f=[];if(d)for(var g=function(p){c(p)},l=function(p,s){d--;f[p]=s;0===d&&e(f)},h=0,n;n=
a[h];h++)n.then(g,t(l,h));else c(void 0)})};b.prototype.then=function(a,c,e){return this.addChildPromise_(m.core.isFunction(a)?a:null,m.core.isFunction(c)?c:null,e)};q.addImplementation(b);b.prototype.thenAlways=function(a,c){var e=function(){try{a.call(c)}catch(d){b.handleRejection_.call(null,d)}};this.addCallbackEntry_({child:null,onRejected:e,onFulfilled:e});return this};b.prototype.thenCatch=function(a,c){return this.addChildPromise_(null,a,c)};b.prototype.catch=b.prototype.thenCatch;b.prototype.cancel=
function(a){this.state_===b.State_.PENDING&&m.async.run(function(){var c=new b.CancellationError(a);c.IS_CANCELLATION_ERROR=!0;this.cancelInternal_(c)},this)};b.prototype.cancelInternal_=function(a){this.state_===b.State_.PENDING&&(this.parent_?this.parent_.cancelChild_(this,a):this.resolve_(b.State_.REJECTED,a))};b.prototype.cancelChild_=function(a,c){if(this.callbackEntries_){for(var e=0,d=-1,f=0,g;g=this.callbackEntries_[f];f++)if(g=g.child)if(e++,g===a&&(d=f),0<=d&&1<e)break;0<=d&&(this.state_===
b.State_.PENDING&&1===e?this.cancelInternal_(c):(e=this.callbackEntries_.splice(d,1)[0],this.executeCallback_(e,b.State_.REJECTED,c)))}};b.prototype.addCallbackEntry_=function(a){this.callbackEntries_&&this.callbackEntries_.length||this.state_!==b.State_.FULFILLED&&this.state_!==b.State_.REJECTED||this.scheduleCallbacks_();this.callbackEntries_||(this.callbackEntries_=[]);this.callbackEntries_.push(a)};b.prototype.addChildPromise_=function(a,c,e){var d={child:null,onFulfilled:null,onRejected:null};
d.child=new b(function(f,g){d.onFulfilled=a?function(l){try{var h=a.call(e,l);f(h)}catch(n){g(n)}}:f;d.onRejected=c?function(l){try{var h=c.call(e,l);!m.core.isDef(h)&&l.IS_CANCELLATION_ERROR?g(l):f(h)}catch(n){g(n)}}:g});d.child.parent_=this;this.addCallbackEntry_(d);return d.child};b.prototype.unblockAndFulfill_=function(a){if(this.state_!==b.State_.BLOCKED)throw Error("CancellablePromise is not blocked.");this.state_=b.State_.PENDING;this.resolve_(b.State_.FULFILLED,a)};b.prototype.unblockAndReject_=
function(a){if(this.state_!==b.State_.BLOCKED)throw Error("CancellablePromise is not blocked.");this.state_=b.State_.PENDING;this.resolve_(b.State_.REJECTED,a)};b.prototype.resolve_=function(a,c){if(this.state_===b.State_.PENDING){if(this===c)a=b.State_.REJECTED,c=new TypeError("CancellablePromise cannot resolve to itself");else{if(q.isImplementedBy(c)){this.state_=b.State_.BLOCKED;c.then(this.unblockAndFulfill_,this.unblockAndReject_,this);return}if(m.core.isObject(c))try{var e=c.then;if(m.core.isFunction(e)){this.tryThen_(c,
e);return}}catch(d){a=b.State_.REJECTED,c=d}}this.result_=c;this.state_=a;this.scheduleCallbacks_();a!==b.State_.REJECTED||c.IS_CANCELLATION_ERROR||b.addUnhandledRejection_(this,c)}};b.prototype.tryThen_=function(a,c){this.state_=b.State_.BLOCKED;var e=this,d=!1,f=function(h){d||(d=!0,e.unblockAndFulfill_(h))},g=function(h){d||(d=!0,e.unblockAndReject_(h))};try{c.call(a,f,g)}catch(l){g(l)}};b.prototype.scheduleCallbacks_=function(){this.executing_||(this.executing_=!0,m.async.run(this.executeCallbacks_,
this))};b.prototype.executeCallbacks_=function(){for(;this.callbackEntries_&&this.callbackEntries_.length;){var a=this.callbackEntries_;this.callbackEntries_=[];for(var c=0;c<a.length;c++)this.executeCallback_(a[c],this.state_,this.result_)}this.executing_=!1};b.prototype.executeCallback_=function(a,c,e){if(c===b.State_.FULFILLED)a.onFulfilled(e);else this.removeUnhandledRejection_(),a.onRejected(e)};b.prototype.removeUnhandledRejection_=function(){var a;if(0<b.UNHANDLED_REJECTION_DELAY)for(a=this;a&&
a.unhandledRejectionId_;a=a.parent_)clearTimeout(a.unhandledRejectionId_),a.unhandledRejectionId_=0;else if(0===b.UNHANDLED_REJECTION_DELAY)for(a=this;a&&a.hadUnhandledRejection_;a=a.parent_)a.hadUnhandledRejection_=!1};b.addUnhandledRejection_=function(a,c){0<b.UNHANDLED_REJECTION_DELAY?a.unhandledRejectionId_=setTimeout(function(){b.handleRejection_.call(null,c)},b.UNHANDLED_REJECTION_DELAY):0===b.UNHANDLED_REJECTION_DELAY&&(a.hadUnhandledRejection_=!0,m.async.run(function(){a.hadUnhandledRejection_&&
b.handleRejection_.call(null,c)}))};b.handleRejection_=m.async.throwException;b.setUnhandledRejectionHandler=function(a){b.handleRejection_=a};b.CancellationError=function(a){function c(e){if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");var d;d=a.call(this,e);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");d=!d||"object"!==typeof d&&"function"!==typeof d?this:d;e&&(d.message=e);return d}u(c,a);return c}(Error);b.CancellationError.prototype.name=
"cancel";r.CancellablePromise=b;r.default=b});
define("frontend-js-spa-web@1.0.10/senna/src/globals/globals",["exports"],function(a){Object.defineProperty(a,"__esModule",{value:!0});a.default={document:document,window:window}});
define("frontend-js-spa-web@1.0.10/metal-uri/src/parseFromAnchor",["exports"],function(b){Object.defineProperty(b,"__esModule",{value:!0});b.default=function(c){var a=document.createElement("a");a.href=c;return{hash:a.hash,hostname:a.hostname,password:a.password,pathname:"/"===a.pathname[0]?a.pathname:"/"+a.pathname,port:a.port,protocol:a.protocol,search:a.search,username:a.username}}});
define("frontend-js-spa-web@1.0.10/metal-uri/src/parse",["exports","metal/src/metal","./parseFromAnchor"],function(b,d,a){Object.defineProperty(b,"__esModule",{value:!0});var e=a&&a.__esModule?a:{default:a};b.default=function(c){return d.core.isFunction(URL)&&URL.length?new URL(c):(0,e.default)(c)}});
define("frontend-js-spa-web@1.0.10/metal-multimap/src/MultiMap",["exports","metal/src/metal"],function(f,g){function h(c,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);c.prototype=Object.create(b&&b.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(c,b):c.__proto__=b)}Object.defineProperty(f,"__esModule",{value:!0});var e=Object.create,k=function(c){function b(){if(!(this instanceof
b))throw new TypeError("Cannot call a class as a function");var a;a=c.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!a||"object"!==typeof a&&"function"!==typeof a?this:a;a.keys=e(null);a.values=e(null);return a}h(b,c);b.prototype.add=function(a,d){this.keys[a.toLowerCase()]=a;this.values[a.toLowerCase()]=this.values[a.toLowerCase()]||[];this.values[a.toLowerCase()].push(d);return this};b.prototype.clear=function(){this.keys=e(null);this.values=
e(null);return this};b.prototype.contains=function(a){return a.toLowerCase()in this.values};b.prototype.disposeInternal=function(){this.values=null};b.prototype.get=function(a){if(a=this.values[a.toLowerCase()])return a[0]};b.prototype.getAll=function(a){return this.values[a.toLowerCase()]};b.prototype.isEmpty=function(){return 0===this.size()};b.prototype.names=function(){var a=this;return Object.keys(this.values).map(function(d){return a.keys[d]})};b.prototype.remove=function(a){delete this.keys[a.toLowerCase()];
delete this.values[a.toLowerCase()];return this};b.prototype.set=function(a,d){this.keys[a.toLowerCase()]=a;this.values[a.toLowerCase()]=[d];return this};b.prototype.size=function(){return this.names().length};b.prototype.toString=function(){return JSON.stringify(this.values)};return b}(g.Disposable);f.default=k});
define("frontend-js-spa-web@1.0.10/metal-uri/src/Uri",["exports","metal/src/metal","./parse","metal-multimap/src/MultiMap"],function(n,k,h,f){Object.defineProperty(n,"__esModule",{value:!0});h=h&&h.__esModule?h:{default:h};var q=f&&f.__esModule?f:{default:f},s=function(){return function(c,a){if(Array.isArray(c))return c;if(Symbol.iterator in Object(c)){var b=[],d=!0,e=!1,g=void 0;try{for(var l=c[Symbol.iterator](),p;!(d=(p=l.next()).done)&&(b.push(p.value),!a||b.length!==a);d=!0);}catch(r){e=!0,g=
r}finally{try{if(!d&&l["return"])l["return"]()}finally{if(e)throw g;}}return b}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}(),m=h.default;f=function(){function c(){var a=0>=arguments.length||void 0===arguments[0]?"":arguments[0];if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");this.url=c.parse(this.maybeAddProtocolAndHostname_(a))}c.prototype.addParametersFromMultiMap=function(a){var b=this;a.names().forEach(function(d){a.getAll(d).forEach(function(e){b.addParameterValue(d,
e)})});return this};c.prototype.addParameterValue=function(a,b){this.ensureQueryInitialized_();k.core.isDef(b)&&(b=String(b));this.query.add(a,b);return this};c.prototype.addParameterValues=function(a,b){var d=this;b.forEach(function(e){return d.addParameterValue(a,e)});return this};c.prototype.ensureQueryInitialized_=function(){var a=this;if(!this.query){this.query=new q.default;var b=this.url.search;b&&b.substring(1).split("\x26").forEach(function(d){d=d.split("\x3d");var e=s(d,2);d=e[0];e=e[1];
k.core.isDef(e)&&(e=c.urlDecode(e));a.addParameterValue(d,e)})}};c.prototype.getHash=function(){return this.url.hash||""};c.prototype.getHost=function(){var a=this.getHostname();if(a){var b=this.getPort();b&&"80"!==b&&(a+=":"+b)}return a};c.prototype.getHostname=function(){var a=this.url.hostname;return a===c.HOSTNAME_PLACEHOLDER?"":a};c.prototype.getOrigin=function(){var a=this.getHost();return a?this.getProtocol()+"//"+a:""};c.prototype.getParameterValue=function(a){this.ensureQueryInitialized_();
return this.query.get(a)};c.prototype.getParameterValues=function(a){this.ensureQueryInitialized_();return this.query.getAll(a)};c.prototype.getParameterNames=function(){this.ensureQueryInitialized_();return this.query.names()};c.getParseFn=function(){return m};c.prototype.getPathname=function(){return this.url.pathname};c.prototype.getPort=function(){return this.url.port};c.prototype.getProtocol=function(){return this.url.protocol};c.prototype.getSearch=function(){var a=this,b="",d="";this.getParameterNames().forEach(function(e){a.getParameterValues(e).forEach(function(g){d+=
e;k.core.isDef(g)&&(d+="\x3d"+encodeURIComponent(g));d+="\x26"})});(d=d.slice(0,-1))&&(b+="?"+d);return b};c.prototype.hasParameter=function(a){this.ensureQueryInitialized_();return this.query.contains(a)};c.prototype.makeUnique=function(){this.setParameterValue(c.RANDOM_PARAM,k.string.getRandomString());return this};c.prototype.maybeAddProtocolAndHostname_=function(a){var b=a;if(-1===a.indexOf("://")&&0!==a.indexOf("javascript:")){b=c.DEFAULT_PROTOCOL;if("/"!==a[0]||"/"!==a[1])b+="//";switch(a.charAt(0)){case ".":case "?":case "#":b+=
c.HOSTNAME_PLACEHOLDER;b=b+"/"+a;break;case "":case "/":"/"!==a[1]&&(b+=c.HOSTNAME_PLACEHOLDER);b+=a;break;default:b+=a}}return b};c.normalizeObject=function(a){var b=a.pathname?a.pathname.length:0;1<b&&"/"===a.pathname[b-1]&&(a.pathname=a.pathname.substr(0,b-1));return a};c.parse=function(a){return c.normalizeObject(m(a))};c.prototype.removeParameter=function(a){this.ensureQueryInitialized_();this.query.remove(a);return this};c.prototype.removeUnique=function(){this.removeParameter(c.RANDOM_PARAM);
return this};c.prototype.setHash=function(a){this.url.hash=a;return this};c.prototype.setHostname=function(a){this.url.hostname=a;return this};c.prototype.setParameterValue=function(a,b){this.removeParameter(a);this.addParameterValue(a,b);return this};c.prototype.setParameterValues=function(a,b){var d=this;this.removeParameter(a);b.forEach(function(e){return d.addParameterValue(a,e)});return this};c.prototype.setPathname=function(a){this.url.pathname=a;return this};c.prototype.setPort=function(a){this.url.port=
a;return this};c.setParseFn=function(a){m=a};c.prototype.setProtocol=function(a){this.url.protocol=a;":"!==this.url.protocol[this.url.protocol.length-1]&&(this.url.protocol+=":");return this};c.prototype.toString=function(){var a="",b=this.getHost();b&&(a+=this.getProtocol()+"//");return a+=b+this.getPathname()+this.getSearch()+this.getHash()};c.joinPaths=function(a){for(var b=arguments.length,d=Array(1<b?b-1:0),e=1;e<b;e++)d[e-1]=arguments[e];"/"===a.charAt(a.length-1)&&(a=a.substring(0,a.length-
1));d=d.map(function(g){return"/"===g.charAt(0)?g.substring(1):g});return[a].concat(d).join("/").replace(/\/$/,"")};c.urlDecode=function(a){return decodeURIComponent(a.replace(/\+/g," "))};return c}();f.DEFAULT_PROTOCOL="http:";f.HOSTNAME_PLACEHOLDER="hostname"+Date.now();f.RANDOM_PARAM="zx";n.default=f});
define("frontend-js-spa-web@1.0.10/metal-ajax/src/Ajax",["exports","metal/src/metal","metal-uri/src/Uri","metal-promise/src/promise/Promise"],function(l,m,e,r){Object.defineProperty(l,"__esModule",{value:!0});var s=e&&e.__esModule?e:{default:e};e=function(){function h(){if(!(this instanceof h))throw new TypeError("Cannot call a class as a function");}h.parseResponseHeaders=function(a){var g=[];if(!a)return g;a=a.split("\r\n");for(var d=0;d<a.length;d++){var c=a[d].indexOf(": ");if(0<c){var k=a[d].substring(0,
c),c=a[d].substring(c+2);g.push({name:k,value:c})}}return g};h.request=function(a,g,d,c,k,n,t,u){var b=new XMLHttpRequest,q=(new r.CancellablePromise(function(f,v){b.onload=function(){if(b.aborted)b.onerror();else f(b)};b.onerror=function(){var p=Error("Request error");p.request=b;v(p)}})).thenCatch(function(f){b.abort();throw f;}).thenAlways(function(){clearTimeout(w)});k&&(a=(new s.default(a)).addParametersFromMultiMap(k).toString());b.open(g,a,!t);u&&(b.withCredentials=!0);c&&c.names().forEach(function(f){b.setRequestHeader(f,
c.getAll(f).join(", "))});b.send(m.core.isDef(d)?d:null);if(m.core.isDefAndNotNull(n))var w=setTimeout(function(){q.cancel("Request timeout")},n);return q};return h}();l.default=e});
define("frontend-js-spa-web@1.0.10/senna/src/errors/errors",["exports"],function(b){Object.defineProperty(b,"__esModule",{value:!0});var a=function c(){if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");};a.INVALID_STATUS="Invalid status code";a.REQUEST_ERROR="Request error";a.REQUEST_TIMEOUT="Request timeout";b.default=a});
define("frontend-js-spa-web@1.0.10/senna/src/utils/utils",["exports","../globals/globals","metal-uri/src/Uri"],function(g,c,e){Object.defineProperty(g,"__esModule",{value:!0});var d=c&&c.__esModule?c:{default:c},h=e&&e.__esModule?e:{default:e};c=function(){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");}b.copyNodeAttributes=function(a,f){Array.prototype.slice.call(a.attributes).forEach(function(k){return f.setAttribute(k.name,k.value)})};b.getCurrentBrowserPath=
function(){return this.getCurrentBrowserPathWithoutHash()+d.default.window.location.hash};b.getCurrentBrowserPathWithoutHash=function(){return d.default.window.location.pathname+d.default.window.location.search};b.getUrlPath=function(a){a=new h.default(a);return a.getPathname()+a.getSearch()+a.getHash()};b.getUrlPathWithoutHash=function(a){a=new h.default(a);return a.getPathname()+a.getSearch()};b.isCurrentBrowserPath=function(a){return a?b.getUrlPathWithoutHash(a)===this.getCurrentBrowserPathWithoutHash():
!1};b.isHtml5HistorySupported=function(){return!(!d.default.window.history||!d.default.window.history.pushState)};b.clearNodeAttributes=function(a){Array.prototype.slice.call(a.attributes).forEach(function(f){return a.removeAttribute(f.name)})};return b}();g.default=c});
define("frontend-js-spa-web@1.0.10/senna/src/cacheable/Cacheable",["exports","metal/src/metal"],function(d,e){function f(c,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);c.prototype=Object.create(a&&a.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(c,a):c.__proto__=a)}Object.defineProperty(d,"__esModule",{value:!0});var g=function(c){function a(){if(!(this instanceof
a))throw new TypeError("Cannot call a class as a function");var b;b=c.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");b=!b||"object"!==typeof b&&"function"!==typeof b?this:b;b.cache=null;b.cacheable=!1;return b}f(a,c);a.prototype.addCache=function(b){this.cacheable&&(this.cache=b);return this};a.prototype.clearCache=function(){this.cache=null;return this};a.prototype.disposeInternal=function(){this.clearCache()};a.prototype.getCache=function(){return this.cache};
a.prototype.isCacheable=function(){return this.cacheable};a.prototype.setCacheable=function(b){b||this.clearCache();this.cacheable=b};return a}(e.Disposable);d.default=g});
define("frontend-js-spa-web@1.0.10/senna/src/screen/Screen",["exports","metal/src/metal","metal-dom/src/all/dom","../cacheable/Cacheable","metal-promise/src/promise/Promise"],function(l,n,p,d,e){function q(c,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);c.prototype=Object.create(a&&a.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(c,a):c.__proto__=
a)}Object.defineProperty(l,"__esModule",{value:!0});var f=e&&e.__esModule?e:{default:e},k=function(c){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");var b;b=c.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");b=!b||"object"!==typeof b&&"function"!==typeof b?this:b;b.id=b.makeId_(n.core.getUid());b.title=null;return b}q(a,c);a.prototype.activate=function(){};a.prototype.beforeDeactivate=function(){};
a.prototype.beforeUpdateHistoryPath=function(b){return b};a.prototype.beforeUpdateHistoryState=function(b){return b};a.prototype.deactivate=function(){};a.prototype.disposeInternal=function(){c.prototype.disposeInternal.call(this)};a.prototype.evaluateScripts=function(b){Object.keys(b).forEach(function(g){b[g].activeChild&&p.globalEval.runScriptsInElement(b[g].activeChild)});return f.default.resolve()};a.prototype.evaluateStyles=function(){return f.default.resolve()};a.prototype.flip=function(b){var g=
this,m=[];Object.keys(b).forEach(function(h){h=b[h].show(g.id);m.push(h)});return f.default.all(m)};a.prototype.getId=function(){return this.id};a.prototype.getSurfaceContent=function(){};a.prototype.getTitle=function(){return this.title};a.prototype.load=function(){return f.default.resolve()};a.prototype.makeId_=function(b){return"screen_"+b};a.prototype.setId=function(b){this.id=b};a.prototype.setTitle=function(b){this.title=b};a.prototype.toString=function(){return this.id};return a}((d&&d.__esModule?
d:{default:d}).default);k.isImplementedBy=function(c){return c instanceof k};l.default=k});
define("frontend-js-spa-web@1.0.10/metal-useragent/src/UA",["exports"],function(d){Object.defineProperty(d,"__esModule",{value:!0});var c=function(){function a(){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");}a.getNativeUserAgent=function(){var b=a.globals.window.navigator;return b&&(b=b.userAgent)?b:""};a.matchUserAgent=function(b){return-1!==a.userAgent.indexOf(b)};a.testUserAgent=function(b){a.userAgent=b;a.isOpera=a.matchUserAgent("Opera")||a.matchUserAgent("OPR");
a.isIe=a.matchUserAgent("Trident")||a.matchUserAgent("MSIE");a.isEdge=a.matchUserAgent("Edge");a.isIeOrEdge=a.isIe||a.isEdge;a.isChrome=(a.matchUserAgent("Chrome")||a.matchUserAgent("CriOS"))&&!a.isOpera&&!a.isEdge;a.isSafari=a.matchUserAgent("Safari")&&!(a.isChrome||a.isOpera||a.isEdge);a.isFirefox=a.matchUserAgent("Firefox")};return a}();c.globals={window:window};c.testUserAgent(c.getNativeUserAgent());d.default=c});
