define("frontend-js-spa-web@1.0.10/senna/src/screen/RequestScreen","exports metal/src/metal metal-ajax/src/Ajax metal-multimap/src/MultiMap metal-promise/src/promise/Promise ../errors/errors ../utils/utils ../globals/globals ./Screen metal-uri/src/Uri metal-useragent/src/UA".split(" "),function(q,u,k,v,w,x,y,z,A,g,B){function f(e){return e&&e.__esModule?e:{default:e}}function C(e,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);
e.prototype=Object.create(b&&b.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(e,b):e.__proto__=b)}Object.defineProperty(q,"__esModule",{value:!0});var D=f(k),E=f(v),F=f(w),l=f(x),G=f(y),r=f(z);k=f(A);var s=f(g),m=f(B);g=function(e){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var a;a=e.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
a=!a||"object"!==typeof a&&"function"!==typeof a?this:a;a.cacheable=!0;a.httpHeaders={"X-PJAX":"true","X-Requested-With":"XMLHttpRequest"};a.httpMethod=b.GET;a.request=null;a.timeout=3E4;return a}C(b,e);b.prototype.assertValidResponseStatusCode=function(a){if(!this.isValidResponseStatusCode(a))throw a=Error(l.default.INVALID_STATUS),a.invalidStatus=!0,a;};b.prototype.beforeUpdateHistoryPath=function(a){var c=this.getRequestPath();return c&&c!==a?c:a};b.prototype.beforeUpdateHistoryState=function(a){return a.senna&&
a.form&&a.redirectPath===a.path?null:a};b.prototype.formatLoadPath=function(a){return m.default.isIeOrEdge&&this.httpMethod===b.GET?(new s.default(a)).makeUnique().toString():a};b.prototype.getHttpHeaders=function(){return this.httpHeaders};b.prototype.getHttpMethod=function(){return this.httpMethod};b.prototype.getRequestPath=function(){var a=this.getRequest();if(a){var c=a.requestPath;(a=this.maybeExtractResponseUrlFromRequest(a))&&(c=a);m.default.isIeOrEdge&&this.httpMethod===b.GET&&(c=(new s.default(c)).removeUnique().toString());
return G.default.getUrlPath(c)}return null};b.prototype.getRequest=function(){return this.request};b.prototype.getTimeout=function(){return this.timeout};b.prototype.isValidResponseStatusCode=function(a){return 200<=a&&399>=a};b.prototype.load=function(a){var c=this,h=this.getCache();if(u.core.isDefAndNotNull(h))return F.default.resolve(h);var h=null,n=this.httpMethod,p=new E.default;Object.keys(this.httpHeaders).forEach(function(d){return p.add(d,c.httpHeaders[d])});r.default.capturedFormElement&&
(h=new FormData(r.default.capturedFormElement),n=b.POST,m.default.isIeOrEdge&&p.add("If-None-Match",'"0"'));var t=this.formatLoadPath(a);return D.default.request(t,n,h,p,null,this.timeout).then(function(d){c.setRequest(d);c.assertValidResponseStatusCode(d.status);n===b.GET&&c.isCacheable()&&c.addCache(d.responseText);d.requestPath=t;return d.responseText}).catch(function(d){switch(d.message){case l.default.REQUEST_TIMEOUT:d.timeout=!0;break;case l.default.REQUEST_ERROR:d.requestError=!0}throw d;})};
b.prototype.maybeExtractResponseUrlFromRequest=function(a){var c=a.responseURL;return c?c:a.getResponseHeader(b.X_REQUEST_URL_HEADER)};b.prototype.setHttpHeaders=function(a){this.httpHeaders=a};b.prototype.setHttpMethod=function(a){this.httpMethod=a.toLowerCase()};b.prototype.setRequest=function(a){this.request=a};b.prototype.setTimeout=function(a){this.timeout=a};return b}(k.default);g.GET="get";g.POST="post";g.X_REQUEST_URL_HEADER="X-Request-URL";q.default=g});
define("frontend-js-spa-web@1.0.10/senna/src/surface/Surface",["exports","../globals/globals","metal/src/metal","metal-dom/src/all/dom","metal-promise/src/promise/Promise"],function(l,f,m,p,q){function k(d){return d&&d.__esModule?d:{default:d}}function r(d,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);d.prototype=Object.create(a&&a.prototype,{constructor:{value:d,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?
Object.setPrototypeOf(d,a):d.__proto__=a)}Object.defineProperty(l,"__esModule",{value:!0});var h=k(f),g=k(p),s=k(q);f=function(d){function a(c){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");var b;b=d.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");b=!b||"object"!==typeof b&&"function"!==typeof b?this:b;if(!c)throw Error("Surface element id not specified. A surface element requires a valid id.");b.activeChild=
null;b.defaultChild=null;b.element=null;b.id=c;b.transitionFn=null;b.defaultChild=b.getChild(a.DEFAULT);b.maybeWrapContentAsDefault_();b.activeChild=b.defaultChild;return b}r(a,d);a.prototype.addContent=function(c,b){var e=this.defaultChild;m.core.isDefAndNotNull(b)&&((e=this.getChild(c))?g.default.removeChildren(e):(e=this.createChild(c),this.transition(e,null)),g.default.append(e,b));var n=this.getElement();n&&e&&g.default.append(n,e);return e};a.prototype.createChild=function(c){var b=h.default.document.createElement("div");
b.setAttribute("id",this.makeId_(c));return b};a.prototype.getChild=function(c){return h.default.document.getElementById(this.makeId_(c))};a.prototype.getElement=function(){return this.element?this.element:this.element=h.default.document.getElementById(this.id)};a.prototype.getId=function(){return this.id};a.prototype.getTransitionFn=function(){return this.transitionFn};a.prototype.makeId_=function(c){return this.id+"-"+c};a.prototype.maybeWrapContentAsDefault_=function(){var c=this.getElement();
if(c&&!this.defaultChild){for(var b=h.default.document.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);this.defaultChild=this.addContent(a.DEFAULT,b);this.transition(null,this.defaultChild)}};a.prototype.setId=function(c){this.id=c};a.prototype.setTransitionFn=function(c){this.transitionFn=c};a.prototype.show=function(c){var b=this.activeChild,e=this.getChild(c);e||(e=this.defaultChild);this.activeChild=e;return this.transition(b,e).thenAlways(function(){b&&b!==e&&g.default.exitDocument(b)})};
a.prototype.remove=function(c){(c=this.getChild(c))&&g.default.exitDocument(c)};a.prototype.toString=function(){return this.id};a.prototype.transition=function(c,b){return s.default.resolve((this.transitionFn||a.defaultTransition).call(this,c,b))};return a}(m.Disposable);f.DEFAULT="default";f.defaultTransition=function(d,a){d&&(d.style.display="none",d.classList.remove("flipped"));a&&(a.style.display="block",a.classList.add("flipped"))};l.default=f});
define("frontend-js-spa-web@1.0.10/senna/src/screen/HtmlScreen","exports metal/src/metal metal-dom/src/all/dom metal-promise/src/promise/Promise ../globals/globals ./RequestScreen ../surface/Surface metal-useragent/src/UA metal-uri/src/Uri ../utils/utils".split(" "),function(q,u,f,p,v,w,l,x,y,z){function g(d){return d&&d.__esModule?d:{default:d}}function A(d,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);d.prototype=Object.create(b&&
b.prototype,{constructor:{value:d,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(d,b):d.__proto__=b)}Object.defineProperty(q,"__esModule",{value:!0});var B=g(p),h=g(v);p=g(w);var C=g(l),D=g(x),E=g(y),n=g(z);l=function(d){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var a;a=d.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!a||"object"!==typeof a&&
"function"!==typeof a?this:a;a.titleSelector="title";return a}A(b,d);b.prototype.activate=function(){d.prototype.activate.call(this);this.releaseVirtualDocument();this.pendingStyles=null};b.prototype.allocateVirtualDocumentForContent=function(a){this.virtualDocument||(this.virtualDocument=h.default.document.createElement("html"));this.copyNodeAttributesFromContent_(a,this.virtualDocument);this.virtualDocument.innerHTML=a};b.prototype.appendStyleIntoDocument_=function(a){f.dom.match(a,b.selectors.stylesTemporary)&&
(this.pendingStyles.push(a),D.default.isIe&&a.href&&(a.href=(new E.default(a.href)).makeUnique().toString()));if(a.id){var c=h.default.document.getElementById(a.id);if(c){c.parentNode.insertBefore(a,c.nextSibling);return}}h.default.document.head.appendChild(a)};b.prototype.assertSameBodyIdInVirtualDocument=function(){var a=this.virtualDocument.querySelector("body");h.default.document.body.id||(h.default.document.body.id="senna_surface_"+u.core.getUid());a&&(a.id=h.default.document.body.id)};b.prototype.copyNodeAttributesFromContent_=
function(a,c){a=a.replace(/[<]\s*html/ig,"\x3csenna");a=a.replace(/\/html\s*\>/ig,"/senna\x3e");c.innerHTML=a;var k=c.querySelector("senna");k&&(n.default.clearNodeAttributes(c),n.default.copyNodeAttributes(k,c))};b.prototype.disposeInternal=function(){this.disposePendingStyles();d.prototype.disposeInternal.call(this)};b.prototype.disposePendingStyles=function(){this.pendingStyles&&this.pendingStyles.forEach(function(a){return f.dom.exitDocument(a)})};b.prototype.evaluateScripts=function(a){var c=
this;return this.evaluateTrackedResources_(f.globalEval.runScriptsInElement,b.selectors.scripts,b.selectors.scriptsTemporary,b.selectors.scriptsPermanent).then(function(){return d.prototype.evaluateScripts.call(c,a)})};b.prototype.evaluateStyles=function(a){var c=this;this.pendingStyles=[];return this.evaluateTrackedResources_(f.globalEvalStyles.runStylesInElement,b.selectors.styles,b.selectors.stylesTemporary,b.selectors.stylesPermanent,this.appendStyleIntoDocument_.bind(this)).then(function(){return d.prototype.evaluateStyles.call(c,
a)})};b.prototype.evaluateTrackedResources_=function(a,c,k,r,F){var s=this;c=this.virtualQuerySelectorAll_(c);var G=this.querySelectorAll_(k);this.querySelectorAll_(r).forEach(function(e){(e=s.getResourceKey_(e))&&(b.permanentResourcesInDoc[e]=!0)});var t=f.dom.buildFragment();c.forEach(function(e){var m=s.getResourceKey_(e);b.permanentResourcesInDoc[m]||t.appendChild(e);m&&f.dom.match(e,r)&&(b.permanentResourcesInDoc[m]=!0)});return new B.default(function(e){a(t,function(){G.forEach(function(m){return f.dom.exitDocument(m)});
e()},F)})};b.prototype.flip=function(a){var c=this;return d.prototype.flip.call(this,a).then(function(){n.default.clearNodeAttributes(document.documentElement);n.default.copyNodeAttributes(c.virtualDocument,document.documentElement)})};b.prototype.getResourceKey_=function(a){return a.id||a.href||a.src||""};b.prototype.getSurfaceContent=function(a){var c=this.virtualDocument.querySelector("#"+a);if(c)return(a=c.querySelector("#"+a+"-"+C.default.DEFAULT))?a.innerHTML:c.innerHTML};b.prototype.getTitleSelector=
function(){return this.titleSelector};b.prototype.load=function(a){var c=this;return d.prototype.load.call(this,a).then(function(k){c.allocateVirtualDocumentForContent(k);c.resolveTitleFromVirtualDocument();c.assertSameBodyIdInVirtualDocument();return k})};b.prototype.virtualQuerySelectorAll_=function(a){return Array.prototype.slice.call(this.virtualDocument.querySelectorAll(a))};b.prototype.querySelectorAll_=function(a){return Array.prototype.slice.call(h.default.document.querySelectorAll(a))};b.prototype.releaseVirtualDocument=
function(){this.virtualDocument=null};b.prototype.resolveTitleFromVirtualDocument=function(){var a=this.virtualDocument.querySelector(this.titleSelector);a&&this.setTitle(a.innerHTML.trim())};b.prototype.setTitleSelector=function(a){this.titleSelector=a};return b}(p.default);l.selectors={scripts:"script[data-senna-track]",scriptsPermanent:'script[data-senna-track\x3d"permanent"]',scriptsTemporary:'script[data-senna-track\x3d"temporary"]',styles:"style[data-senna-track],link[data-senna-track]",stylesPermanent:'style[data-senna-track\x3d"permanent"],link[data-senna-track\x3d"permanent"]',
stylesTemporary:'style[data-senna-track\x3d"temporary"],link[data-senna-track\x3d"temporary"]'};l.permanentResourcesInDoc={};q.default=l});
define("frontend-js-spa-web@1.0.10/liferay/util/Utils.es",["exports"],function(c){Object.defineProperty(c,"__esModule",{value:!0});var e=function(){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");}b.getPortletBoundaryId=function(a){return"p_p_id_"+a+"_"};b.getPortletBoundaryIds=function(a){return a.map(function(d){return b.getPortletBoundaryId(d)})};b.resetAllPortlets=function(){b.getPortletBoundaryIds(Liferay.Portlet.list).forEach(function(a,d,f){if(a=
document.querySelector("#"+a))Liferay.Portlet.destroy(a),a.portletProcessed=!1});Liferay.Portlet.readyCounter=0};return b}();c.default=e});
define("frontend-js-spa-web@1.0.10/liferay/screen/EventScreen.es",["exports","senna/src/screen/HtmlScreen","senna/src/globals/globals","metal-promise/src/promise/Promise","../util/Utils.es"],function(h,e,f,k,m){function g(c){return c&&c.__esModule?c:{default:c}}function n(c,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);c.prototype=Object.create(b&&b.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});
b&&(Object.setPrototypeOf?Object.setPrototypeOf(c,b):c.__proto__=b)}Object.defineProperty(h,"__esModule",{value:!0});e=g(e);var p=g(f),q=g(m);f=function(c){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var a;a=c.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!a||"object"!==typeof a&&"function"!==typeof a?this:a;a.cacheable=!1;a.timeout=Liferay.PropsValues.JAVASCRIPT_SINGLE_PAGE_APPLICATION_TIMEOUT;
return a}n(b,c);b.prototype.dispose=function(){c.prototype.dispose.call(this);Liferay.fire("screenDispose",{app:Liferay.SPA.app,screen:this})};b.prototype.activate=function(){c.prototype.activate.call(this);Liferay.fire("screenActivate",{app:Liferay.SPA.app,screen:this})};b.prototype.addCache=function(a){c.prototype.addCache.call(this,a);this.cacheLastModified=(new Date).getTime()};b.prototype.checkRedirectPath=function(a){var d=Liferay.SPA.app;p.default.capturedFormElement||d.findRoute(a)||(window.location.href=
a)};b.prototype.deactivate=function(){c.prototype.deactivate.call(this);Liferay.fire("screenDeactivate",{app:Liferay.SPA.app,screen:this})};b.prototype.beforeScreenFlip=function(){Liferay.fire("beforeScreenFlip",{app:Liferay.SPA.app,screen:this})};b.prototype.copyBodyAttributes=function(){var a=this.virtualDocument.querySelector("body");document.body.className=a.className;document.body.onload=a.onload};b.prototype.flip=function(a){var d=this;this.copyBodyAttributes();return k.CancellablePromise.resolve(q.default.resetAllPortlets()).then(k.CancellablePromise.resolve(this.beforeScreenFlip())).then(c.prototype.flip.call(this,
a)).then(function(){d.runBodyOnLoad();Liferay.fire("screenFlip",{app:Liferay.SPA.app,screen:d})})};b.prototype.getCache=function(){var a=Liferay.SPA.app;return a.isCacheEnabled()&&!a.isScreenCacheExpired(this)?c.prototype.getCache.call(this):null};b.prototype.getCacheLastModified=function(){return this.cacheLastModified};b.prototype.isValidResponseStatusCode=function(a){var d=Liferay.SPA.app.getValidStatusCodes();return c.prototype.isValidResponseStatusCode.call(this,a)||-1<d.indexOf(a)};b.prototype.load=
function(a){var d=this;return c.prototype.load.call(this,a).then(function(l){var r=d.beforeUpdateHistoryPath(a);d.checkRedirectPath(r);Liferay.fire("screenLoad",{app:Liferay.SPA.app,content:l,screen:d});return l})};b.prototype.runBodyOnLoad=function(){var a=document.body.onload;a&&a()};return b}(e.default);h.default=f});
define("frontend-js-spa-web@1.0.10/liferay/screen/ActionURLScreen.es",["exports","./EventScreen.es","metal-uri/src/Uri","senna/src/utils/utils"],function(g,d,e,h){function f(a){return a&&a.__esModule?a:{default:a}}function k(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,
b):a.__proto__=b)}Object.defineProperty(g,"__esModule",{value:!0});d=f(d);var l=f(e),m=f(h);e=function(a){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var c;c=a.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");c=!c||"object"!==typeof c&&"function"!==typeof c?this:c;c.httpMethod="POST";return c}k(b,a);b.prototype.getRequestPath=function(){if(this.getRequest()){var c=new l.default(a.prototype.getRequestPath.call(this));
"1"===c.getParameterValue("p_p_lifecycle")&&c.setParameterValue("p_p_lifecycle","0");return m.default.getUrlPath(c.toString())}return null};return b}(d.default);g.default=e});
define("frontend-js-spa-web@1.0.10/senna/src/route/Route",["exports","metal/src/metal"],function(e,d){Object.defineProperty(e,"__esModule",{value:!0});var f=function(){function c(b,a){if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");if(!d.core.isDefAndNotNull(b))throw Error("Route path not specified.");if(!d.core.isFunction(a))throw Error("Route handler is not a function.");this.handler=a;this.path=b}c.prototype.getHandler=function(){return this.handler};c.prototype.getPath=
function(){return this.path};c.prototype.matchesPath=function(b){var a=this.path;return d.core.isString(a)?b===a:d.core.isFunction(a)?a(b):a instanceof RegExp?-1<b.search(a):!1};return c}();e.default=f});
define("frontend-js-spa-web@1.0.10/senna/src/app/App","exports metal/src/metal metal-dom/src/all/dom metal-promise/src/promise/Promise metal-events/src/events ../utils/utils ../globals/globals ../route/Route ../screen/Screen ../surface/Surface metal-uri/src/Uri".split(" "),function(t,p,r,w,u,x,y,z,A,B,C){function l(h){return h&&h.__esModule?h:{default:h}}function D(h,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);h.prototype=
Object.create(b&&b.prototype,{constructor:{value:h,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(h,b):h.__proto__=b)}Object.defineProperty(t,"__esModule",{value:!0});var m=l(r),n=l(w),k=l(x),e=l(y),v=l(z),s=l(A),E=l(B),F=l(C);r=function(h){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var a;a=h.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!a||
"object"!==typeof a&&"function"!==typeof a?this:a;a.activeScreen=null;a.activePath=null;a.allowPreventNavigate=!0;a.basePath="";a.captureScrollPositionFromScrollEvent=!0;a.defaultTitle=e.default.document.title;a.formSelector='form[enctype\x3d"multipart/form-data"]:not([data-senna-off])';a.linkSelector="a:not([data-senna-off])";a.loadingCssClass="senna-loading";a.nativeScrollRestorationSupported="scrollRestoration"in e.default.window.history;a.pendingNavigate=null;a.popstateScrollLeft=0;a.popstateScrollTop=
0;a.redirectPath=null;a.routes=[];a.screens={};a.skipLoadPopstate=!1;a.surfaces={};a.updateScrollPosition=!0;a.appEventHandlers_=new u.EventHandler;a.appEventHandlers_.add(m.default.on(e.default.window,"scroll",a.onScroll_.bind(a)),m.default.on(e.default.window,"load",a.onLoad_.bind(a)),m.default.on(e.default.window,"popstate",a.onPopstate_.bind(a)));a.on("startNavigate",a.onStartNavigate_);a.on("beforeNavigate",a.onBeforeNavigate_);a.on("beforeNavigate",a.onBeforeNavigateDefault_,!0);a.setLinkSelector(a.linkSelector);
a.setFormSelector(a.formSelector);return a}D(b,h);b.prototype.addRoutes=function(a){var c=this;Array.isArray(a)||(a=[a]);a.forEach(function(d){d instanceof v.default||(d=new v.default(d.path,d.handler));c.routes.push(d)});return this};b.prototype.addSurfaces=function(a){var c=this;Array.isArray(a)||(a=[a]);a.forEach(function(d){p.core.isString(d)&&(d=new E.default(d));c.surfaces[d.getId()]=d});return this};b.prototype.canNavigate=function(a){var c=k.default.getUrlPath(a);a=new F.default(a);return this.isLinkSameOrigin_(a.getHostname())&&
this.isSameBasePath_(c)&&this.findRoute(c)?!0:!1};b.prototype.clearScreensCache=function(){var a=this;Object.keys(this.screens).forEach(function(c){c===a.activePath?a.activeScreen.clearCache():a.removeScreen(c)})};b.prototype.createScreenInstance=function(a,c){if(!this.pendingNavigate&&a===this.activePath)return this.activeScreen;var d=this.screens[a];d||(d=c.getHandler(),d=d===s.default||s.default.isImplementedBy(d.prototype)?new d:d(c)||new s.default);return d};b.prototype.disposeInternal=function(){this.activeScreen&&
this.removeScreen(this.activePath);this.clearScreensCache();this.formEventHandler_.removeListener();this.linkEventHandler_.removeListener();this.appEventHandlers_.removeAllListeners();h.prototype.disposeInternal.call(this)};b.prototype.dispatch=function(){return this.navigate(k.default.getCurrentBrowserPath(),!0)};b.prototype.doNavigate_=function(a,c){var d=this;if(this.activeScreen&&this.activeScreen.beforeDeactivate())return this.pendingNavigate=n.default.reject(new n.default.CancellationError("Cancelled by active screen"));
var f=this.findRoute(a);if(!f)return this.pendingNavigate=n.default.reject(new n.default.CancellationError("No route for "+a));this.stopPendingNavigate_();var g=this.createScreenInstance(a,f);return g.load(a).then(function(){d.activeScreen&&d.activeScreen.deactivate();d.prepareNavigateHistory_(a,g,c);d.prepareNavigateSurfaces_(g,d.surfaces)}).then(function(){return g.evaluateStyles(d.surfaces)}).then(function(){return g.flip(d.surfaces)}).then(function(){return g.evaluateScripts(d.surfaces)}).then(function(){return d.syncScrollPositionSyncThenAsync_()}).then(function(){return d.finalizeNavigate_(a,
g)}).catch(function(q){d.handleNavigateError_(a,g,q);throw q;})};b.prototype.finalizeNavigate_=function(a,c){c.activate();this.activeScreen&&!this.activeScreen.isCacheable()&&this.activeScreen!==c&&this.removeScreen(this.activePath);this.activePath=a;this.activeScreen=c;this.screens[a]=c;this.pendingNavigate=null;e.default.capturedFormElement=null};b.prototype.findRoute=function(a){if(-1<a.lastIndexOf("#")&&k.default.isCurrentBrowserPath(a))return null;a=k.default.getUrlPathWithoutHash(a);a=k.default.getUrlPathWithoutHash(a.substr(this.basePath.length));
for(var c=0;c<this.routes.length;c++){var d=this.routes[c];if(d.matchesPath(a))return d}return null};b.prototype.getAllowPreventNavigate=function(){return this.allowPreventNavigate};b.prototype.getBasePath=function(){return this.basePath};b.prototype.getDefaultTitle=function(){return this.defaultTitle};b.prototype.getFormSelector=function(){return this.formSelector};b.prototype.getLinkSelector=function(){return this.linkSelector};b.prototype.getLoadingCssClass=function(){return this.loadingCssClass};
b.prototype.getUpdateScrollPosition=function(){return this.updateScrollPosition};b.prototype.handleNavigateError_=function(a,c,d){k.default.isCurrentBrowserPath(a)||this.removeScreen(a)};b.prototype.hasRoutes=function(){return 0<this.routes.length};b.prototype.isLinkSameOrigin_=function(a){return a===e.default.window.location.hostname};b.prototype.isSameBasePath_=function(a){return 0===a.indexOf(this.basePath)};b.prototype.lockHistoryScrollPosition_=function(){var a=e.default.window.history.state;
if(a){var c=!1,d=function g(){e.default.document.removeEventListener("scroll",g,!1);c||(e.default.window.scrollTo(a.scrollLeft,a.scrollTop),c=!0)};p.async.nextTick(d);e.default.document.addEventListener("scroll",d,!1)}};b.prototype.maybeDisableNativeScrollRestoration=function(){this.nativeScrollRestorationSupported&&(this.nativeScrollRestoration_=e.default.window.history.scrollRestoration,e.default.window.history.scrollRestoration="manual")};b.prototype.maybeNavigate_=function(a,c){if(this.canNavigate(a)&&
(!this.allowPreventNavigate||!c.defaultPrevented)){e.default.capturedFormElement=c.capturedFormElement;var d=!1;try{this.navigate(k.default.getUrlPath(a))}catch(f){d=!0}d||c.preventDefault()}};b.prototype.maybeRepositionScrollToHashedAnchor=function(){var a=e.default.window.location.hash;a&&(a=e.default.document.getElementById(a.substring(1)))&&e.default.window.scrollTo(a.offsetLeft,a.offsetTop)};b.prototype.maybeRestoreNativeScrollRestoration=function(){this.nativeScrollRestorationSupported&&this.nativeScrollRestoration_&&
(e.default.window.history.scrollRestoration=this.nativeScrollRestoration_)};b.prototype.navigate=function(a,c){if(!k.default.isHtml5HistorySupported())throw Error("HTML5 History is not supported. Senna will not intercept navigation.");a===this.activePath&&(c=!0);this.emit("beforeNavigate",{path:a,replaceHistory:!!c});return this.pendingNavigate};b.prototype.onBeforeNavigate_=function(a){e.default.capturedFormElement&&(a.form=e.default.capturedFormElement)};b.prototype.onBeforeNavigateDefault_=function(a){this.pendingNavigate&&
this.pendingNavigate.path===a.path||this.emit("startNavigate",{form:a.form,path:a.path,replaceHistory:a.replaceHistory})};b.prototype.onDocClickDelegate_=function(a){a.altKey||a.ctrlKey||a.metaKey||a.shiftKey||a.button||this.maybeNavigate_(a.delegateTarget.href,a)};b.prototype.onDocSubmitDelegate_=function(a){var c=a.delegateTarget;"get"!==c.method&&(a.capturedFormElement=c,this.maybeNavigate_(c.action,a))};b.prototype.onLoad_=function(){var a=this;this.skipLoadPopstate=!0;setTimeout(function(){a.skipLoadPopstate=
!1},0);this.maybeRepositionScrollToHashedAnchor()};b.prototype.onPopstate_=function(a){this.skipLoadPopstate||((a=a.state,a)?a.senna&&(this.popstateScrollTop=a.scrollTop,this.popstateScrollLeft=a.scrollLeft,this.nativeScrollRestorationSupported||this.lockHistoryScrollPosition_(),this.navigate(a.path,!0)):e.default.window.location.hash?(this.redirectPath&&!k.default.isCurrentBrowserPath(this.redirectPath)&&this.reloadPage(),this.maybeRepositionScrollToHashedAnchor()):this.reloadPage())};b.prototype.onScroll_=
function(){this.captureScrollPositionFromScrollEvent&&this.saveHistoryCurrentPageScrollPosition_()};b.prototype.onStartNavigate_=function(a){var c=this;this.maybeDisableNativeScrollRestoration();this.captureScrollPositionFromScrollEvent=!1;m.default.addClasses(e.default.document.documentElement,this.loadingCssClass);var d={form:a.form,path:a.path};this.pendingNavigate=this.doNavigate_(a.path,a.replaceHistory).catch(function(f){d.error=f;throw f;}).thenAlways(function(){c.pendingNavigate||(m.default.removeClasses(e.default.document.documentElement,
c.loadingCssClass),c.maybeRestoreNativeScrollRestoration(),c.captureScrollPositionFromScrollEvent=!0);c.emit("endNavigate",d)});this.pendingNavigate.path=a.path};b.prototype.prefetch=function(a){var c=this,d=this.findRoute(a);if(!d)return n.default.reject(new n.default.CancellationError("No route for "+a));var f=this.createScreenInstance(a,d);return f.load(a).then(function(){return c.screens[a]=f}).catch(function(g){c.handleNavigateError_(a,f,g);throw g;})};b.prototype.prepareNavigateHistory_=function(a,
c,d){var f=c.getTitle();p.core.isString(f)||(f=this.getDefaultTitle());var g=c.beforeUpdateHistoryPath(a);a={form:p.core.isDefAndNotNull(e.default.capturedFormElement),redirectPath:g,path:a,senna:!0,scrollTop:0,scrollLeft:0};d&&(a.scrollTop=this.popstateScrollTop,a.scrollLeft=this.popstateScrollLeft);this.updateHistory_(f,g,c.beforeUpdateHistoryState(a),d);this.redirectPath=g};b.prototype.prepareNavigateSurfaces_=function(a,c){Object.keys(c).forEach(function(d){var f=a.getSurfaceContent(d);c[d].addContent(a.getId(),
f)})};b.prototype.reloadPage=function(){e.default.window.location.reload()};b.prototype.removeRoute=function(a){return p.array.remove(this.routes,a)};b.prototype.removeScreen=function(a){var c=this,d=this.screens[a];d&&(Object.keys(this.surfaces).forEach(function(f){return c.surfaces[f].remove(d.getId())}),d.dispose(),delete this.screens[a])};b.prototype.saveHistoryCurrentPageScrollPosition_=function(){var a=e.default.window.history.state;a&&a.senna&&(a.scrollTop=e.default.window.pageYOffset,a.scrollLeft=
e.default.window.pageXOffset,e.default.window.history.replaceState(a,null,null))};b.prototype.setAllowPreventNavigate=function(a){this.allowPreventNavigate=a};b.prototype.setBasePath=function(a){this.basePath=a};b.prototype.setDefaultTitle=function(a){this.defaultTitle=a};b.prototype.setFormSelector=function(a){this.formSelector=a;this.formEventHandler_&&this.formEventHandler_.removeListener();this.formEventHandler_=m.default.delegate(document,"submit",this.formSelector,this.onDocSubmitDelegate_.bind(this))};
b.prototype.setLinkSelector=function(a){this.linkSelector=a;this.linkEventHandler_&&this.linkEventHandler_.removeListener();this.linkEventHandler_=m.default.delegate(document,"click",this.linkSelector,this.onDocClickDelegate_.bind(this))};b.prototype.setLoadingCssClass=function(a){this.loadingCssClass=a};b.prototype.setUpdateScrollPosition=function(a){this.updateScrollPosition=a};b.prototype.stopPendingNavigate_=function(){this.pendingNavigate&&(this.pendingNavigate.cancel("Cancel pending navigation"),
this.pendingNavigate=null)};b.prototype.syncScrollPositionSyncThenAsync_=function(){var a=this,c=e.default.window.history.state;if(c){var d=c.scrollTop,f=c.scrollLeft,g=function(){a.updateScrollPosition&&e.default.window.scrollTo(f,d)};return new n.default(function(q){return g()&p.async.nextTick(function(){return g()&q()})})}};b.prototype.updateHistory_=function(a,c,d,f){f?e.default.window.history.replaceState(d,a,c):e.default.window.history.pushState(d,a,c);e.default.document.title=a};return b}(u.EventEmitter);
t.default=r});
define("frontend-js-spa-web@1.0.10/liferay/surface/Surface.es",["exports","metal/src/core","metal-dom/src/dom","senna/src/surface/Surface"],function(g,e,h,k){function f(a){return a&&a.__esModule?a:{default:a}}function l(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?Object.setPrototypeOf(a,
b):a.__proto__=b)}Object.defineProperty(g,"__esModule",{value:!0});var m=f(e),n=f(h);e=function(a){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var c=a.apply(this,arguments);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return!c||"object"!==typeof c&&"function"!==typeof c?this:c}l(b,a);b.prototype.addContent=function(c,d){m.default.isString(d)&&(d=n.default.buildFragment(d));Liferay.DOMTaskRunner.runTasks(d);
return a.prototype.addContent.call(this,c,d)};return b}(f(k).default);g.default=e});
define("frontend-js-spa-web@1.0.10/liferay/app/App.es","exports senna/src/app/App metal/src/core metal-dom/src/dom ../util/Utils.es ../surface/Surface.es".split(" "),function(h,f,g,l,m,n){function e(c){return c&&c.__esModule?c:{default:c}}function p(c,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function, not "+typeof b);c.prototype=Object.create(b&&b.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});b&&(Object.setPrototypeOf?
Object.setPrototypeOf(c,b):c.__proto__=b)}Object.defineProperty(h,"__esModule",{value:!0});f=e(f);var q=e(g),k=e(l),r=e(m),s=e(n);g=function(c){function b(){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var a;a=c.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");a=!a||"object"!==typeof a&&"function"!==typeof a?this:a;a.portletsBlacklist={};a.validStatusCodes=[];a.setFormSelector('form:not([target\x3d"_blank"]):not([data-senna-off]):not([data-resource-href])');
a.setLinkSelector('a:not([target\x3d"_blank"]):not([data-senna-off]):not([data-resource-href])');a.setLoadingCssClass("lfr-spa-loading");a.on("beforeNavigate",a.onBeforeNavigate);a.on("endNavigate",a.onEndNavigate);a.on("startNavigate",a.onStartNavigate);Liferay.on("io:complete",a.onLiferayIOComplete,a);var d=document.body;d.id||(d.id="senna_surface"+q.default.getUid());a.addSurfaces(new s.default(d.id));k.default.append(d,'\x3cdiv class\x3d"lfr-spa-loading-bar"\x3e\x3c/div\x3e');return a}p(b,c);
b.prototype.getCacheExpirationTime=function(){return Liferay.SPA.cacheExpirationTime};b.prototype.getValidStatusCodes=function(){return this.validStatusCodes};b.prototype.isCacheEnabled=function(){return-1<this.getCacheExpirationTime()};b.prototype.isInPortletBlacklist=function(a){return Object.keys(this.portletsBlacklist).some(function(d){d=r.default.getPortletBoundaryId(d);d=document.querySelectorAll('[id^\x3d"'+d+'"]');return Array.prototype.slice.call(d).some(function(t){return k.default.contains(t,
a)})})};b.prototype.isScreenCacheExpired=function(a){return(new Date).getTime()-a.getCacheLastModified()>this.getCacheExpirationTime()};b.prototype.onBeforeNavigate=function(a){(Liferay.SPA.clearScreensCache||a.form)&&this.clearScreensCache();Liferay.fire("beforeNavigate",{app:this,path:a.path})};b.prototype.onDocClickDelegate_=function(a){this.isInPortletBlacklist(a.delegateTarget)||c.prototype.onDocClickDelegate_.call(this,a)};b.prototype.onDocSubmitDelegate_=function(a){this.isInPortletBlacklist(a.delegateTarget)||
c.prototype.onDocSubmitDelegate_.call(this,a)};b.prototype.onEndNavigate=function(a){Liferay.fire("endNavigate",{app:this,error:a.error,path:a.path});if(a.error){if(a.error.invalidStatus||a.error.requestError||a.error.timeout)a.form?a.form.submit():window.location.href=a.path}else Liferay.Layout&&Liferay.Data.layoutConfig&&Liferay.Layout.init();AUI().Get._insertCache={};Liferay.DOMTaskRunner.reset()};b.prototype.onLiferayIOComplete=function(){this.clearScreensCache()};b.prototype.onStartNavigate=
function(a){Liferay.fire("startNavigate",{app:this,path:a.path})};b.prototype.setPortletsBlacklist=function(a){this.portletsBlacklist=a};b.prototype.setValidStatusCodes=function(a){this.validStatusCodes=a};return b}(f.default);h.default=g});
define("frontend-js-spa-web@1.0.10/liferay/screen/RenderURLScreen.es",["exports","./EventScreen.es"],function(e,d){function f(c,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function, not "+typeof a);c.prototype=Object.create(a&&a.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});a&&(Object.setPrototypeOf?Object.setPrototypeOf(c,a):c.__proto__=a)}Object.defineProperty(e,"__esModule",{value:!0});var g=function(c){function a(){if(!(this instanceof
a))throw new TypeError("Cannot call a class as a function");var b;b=c.call(this);if(!this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");b=!b||"object"!==typeof b&&"function"!==typeof b?this:b;b.cacheable=!0;return b}f(a,c);return a}((d&&d.__esModule?d:{default:d}).default);e.default=g});
define("frontend-js-spa-web@1.0.10/liferay/init.es","exports ./screen/ActionURLScreen.es ./app/App.es metal/src/async/async senna/src/globals/globals ./screen/RenderURLScreen.es metal-uri/src/Uri senna/src/utils/utils".split(" "),function(k,m,n,p,q,r,s,t){function e(d){return d&&d.__esModule?d:{default:d}}Object.defineProperty(k,"__esModule",{value:!0});var u=e(m),v=e(n),w=e(p),g=e(q),x=e(r),h=e(s),y=e(t),l=function(d){var b=new v.default;b.addRoutes([{handler:u.default,path:function(c){c=new h.default(c);
var a=(new h.default(Liferay.SPA.loginRedirect)).getHostname()||window.location.hostname;return b.isLinkSameOrigin_(a)?"1"===c.getParameterValue("p_p_lifecycle"):!1}},{handler:x.default,path:function(c){if(0===c.indexOf(themeDisplay.getPathMain())||Liferay.SPA.excludedPaths.some(function(f){return 0===c.indexOf(f)}))return!1;var a=(new h.default(c)).getParameterValue("p_p_lifecycle");return"0"===a||!a}}]);Liferay.Util.submitForm=function(c){w.default.nextTick(function(){var a=c.getDOM(),f=a.action;
b.canNavigate(f)&&"get"!==a.method&&!b.isInPortletBlacklist(a)?(Liferay.Util._submitLocked=!1,g.default.capturedFormElement=a,b.navigate(y.default.getUrlPath(f))):a.submit()})};Liferay.SPA.app=b;Liferay.fire("SPAReady");return b};k.default={init:function(d){var b=this;"loading"==g.default.document.readyState?g.default.document.addEventListener("DOMContentLoaded",function(){d.call(b,l())}):d.call(this,l())}}});
