AUI.add("liferay-product-navigation-control-menu",function(b){Liferay.ControlMenu={init:function(a){if(a=b.one(a)){this._namespace=a.attr("data-namespace");Liferay.Util.toggleControls(a);var c=a.on(["focus","mousemove","touchstart"],function(d){Liferay.fire("initLayout");c.detach()})}}}},"",{requires:["aui-node","aui-overlay-mask-deprecated","event-move","event-touch","liferay-menu-toggle"]});
AUI.add("liferay-navigation",function(e){var n=e.Node,r=e.Lang,p=Liferay.STATUS_CODE,q=e.Component.create({ATTRS:{hasAddLayoutPermission:{value:!1},isAddable:{getter:function(a){return this.get("hasAddLayoutPermission")&&this.get("navBlock").hasClass("modify-pages")},value:!1},isModifiable:{getter:function(a){return this.get("navBlock").hasClass("modify-pages")},value:!1},isSortable:{getter:function(a){return this.get("navBlock").hasClass("sort-pages")},value:!1},layoutIds:{value:[]},layoutSetBranchId:{value:0},
navBlock:{lazyAdd:!1,setter:function(a){a=e.one(a);a||(a=e.Attribute.INVALID_VALUE);return a},value:null}},EXTENDS:e.Base,NAME:"navigation",prototype:{TPL_DELETE_BUTTON:'\x3cspan class\x3d"delete-tab"\x3e\x26times;\x3c/span\x3e',initializer:function(a){var b=this.get("navBlock");if(b){this._updateURL=themeDisplay.getPathMain()+"/portal/edit_layout?p_auth\x3d"+Liferay.authToken;a=Liferay.Data.NAV_LIST_SELECTOR||"\x3e ul";var c=Liferay.Data.NAV_ITEM_SELECTOR||a+"\x3e li",d=Liferay.Data.NAV_ITEM_CHILD_TOGGLE_SELECTOR||
"\x3e span",h=b.one(a),b=b.all(c),k=this.get("layoutIds"),f=[];b.each(function(g,l){var m=k[l];m&&(g.setData("layoutId",m.id),m.deletable&&f.push("lfr-nav-deletable"),m.sortable&&f.push("lfr-nav-sortable"),f.length&&(g.addClass(f.join(" ")),f.length=0))});this._navItemChildToggleSelector=d;this._navItemSelector=c;this._navListSelector=a;this._navList=h;this._makeDeletable();this._makeSortable();this._tempTab=this._createTempTab('\x3ca href\x3d"{url}"\x3e\x3cspan\x3e{pageTitle}\x3c/span\x3e\x3c/a\x3e');
this._tempChildTab=this._createTempTab('\x3ca href\x3d"{url}"\x3e{pageTitle}\x3c/a\x3e')}},_afterMakeSortable:function(a){a.delegate.dd.removeInvalid("a")},_cancelPage:function(a){var b=a.actionNode,c=a.field,d=a.listItem,h=a.toolbar,k=this.get("navBlock");b?(b.show(),c.val(a.prevVal)):d.remove(!0);h.destroy();k.one("li")||k.hide()},_clearTempPage:function(){this._tempTab.remove();this._tempChildTab.remove()},_createDeleteButton:function(a){a.append(this.TPL_DELETE_BUTTON)},_createTempTab:function(a){a=
r.sub(a,{pageTitle:"",url:"#"});var b=n.create("\x3cli\x3e");b.append(a);return b},_deleteButton:function(a){var b=this;e.instanceOf(a,e.NodeList)||(a=e.all(a));a.each(function(c,d){c.hasClass("lfr-nav-deletable")&&b._createDeleteButton(c)})},_displayNotice:function(a,b,c,d){(new Liferay.Notice({closeText:!1,content:a+'\x3cbutton class\x3d"close" type\x3d"button"\x3e\x26times;\x3c/button\x3e',noticeClass:"hide",timeout:c||1E4,toggleText:!1,type:b||"warning",useAnimation:r.isValue(d)?d:!0})).show()},
_handleKeyDown:function(a){var b=a.currentTarget;!a.isKey("DELETE")||b.hasClass("selected")||b.ancestor("li.selected")||this._removePage(a)},_hoverNavItem:function(a){a.currentTarget.toggleClass("lfr-nav-hover","mouseenter"==a.type)},_makeDeletable:function(){if(this.get("isModifiable")){var a=this.get("navBlock"),b=this._navItemSelector,c=a.all(b).filter(function(d,h){return!d.hasClass("selected")});a.delegate(["click","touchstart"],e.bind("_removePage",this),".delete-tab");a.delegate("keydown",
e.bind("_handleKeyDown",this),b);a.delegate(["mouseenter","mouseleave"],this._hoverNavItem,".lfr-nav-deletable",this);this._deleteButton(c)}},_onAddPage:function(a){var b=a.data;this._clearTempPage();var c=this.get("navBlock");c.show();a=r.sub(b.parentLayoutId?'\x3ca href\x3d"{url}"\x3e{pageTitle}\x3c/a\x3e':'\x3ca href\x3d"{url}"\x3e\x3cspan\x3e{pageTitle}\x3c/span\x3e\x3c/a\x3e',{pageTitle:b.title,url:b.url});var d=n.create(a);a=b.parentLayoutId?n.create("\x3cli\x3e"):n.create('\x3cli class\x3d"add-page"\x3e\x3c/li\x3e');
a.setData("layoutId",b.layoutId);a.append(d);b.parentLayoutId?(b=c.one("#layout_"+b.parentLayoutId))&&(b=b.one("ul"))&&b.append(a):(a.addClass("lfr-nav-deletable lfr-nav-sortable sortable-item"),this._createDeleteButton(a),c.one("ul").append(a));Liferay.fire("navigation",{item:a,type:"add"})},_onPreviewPageTitle:function(a){a=a.data;if(""===a.name||a.hidden)this._clearTempPage();else{var b=this.get("navBlock");if(a.parentLayoutId){if(b=b.one("#layout_"+a.parentLayoutId))if(b=b.one("ul"))this._tempChildTab.one("a").text(a.name),
b.append(this._tempChildTab)}else this._tempTab.one("span").text(a.name),b.one("ul").append(this._tempTab)}},_optionsOpen:!0,_updateURL:""}});Liferay.provide(q,"_makeSortable",function(){var a=this;if(a.get("isSortable")&&a._navList){var b=new e.Sortable({container:a._navList,moveType:"move",nodes:".lfr-nav-sortable",opacity:".5",opacityNode:"currentNode"});b.plug(e.Plugin.DDWinScroll,{horizontal:!1,vertical:!0});b.delegate.on("drag:end",function(c){c=c.target.get("node");a._saveSortables(c)});b.delegate.on("drag:start",
function(c){c=c.target;c.get("dragNode").addClass("lfr-navigation-proxy");a._nextPageNode=c.get("node").next()});a._afterMakeSortable(b)}},["dd-scroll","liferay-sortable"],!0);Liferay.provide(q,"_removePage",function(a){var b=this,c=b.get("navBlock"),d=a.currentTarget.ancestor("li");if(confirm('Are\x20you\x20sure\x20you\x20want\x20to\x20delete\x20this\x20page\x3f')){var h=function(f){b._displayNotice(f.message)},k=function(f){Liferay.fire("navigation",{item:d,type:"delete"});d.remove(!0);c.one("ul li")||
c.hide()};a={cmd:"delete",doAsUserId:themeDisplay.getDoAsUserIdEncoded(),groupId:themeDisplay.getSiteGroupId(),layoutId:d.getData("layoutId"),layoutSetBranchId:b.get("layoutSetBranchId"),p_auth:Liferay.authToken,privateLayout:themeDisplay.isPrivateLayout()};e.io.request(b._updateURL,{data:a,dataType:"JSON",on:{failure:function(){h({message:'Your\x20request\x20failed\x20to\x20complete\x2e',status:p.BAD_REQUEST})},success:function(f,g,l){f=this.get("responseData");g=h;f.status===p.OK&&(g=k);g(f)}}})}},
["aui-io-request","liferay-notice"],!0);Liferay.provide(q,"_saveSortables",function(a){var b=this,c=-1,d=a.next();d&&(c=d.getData("layoutId"));var d=-1,h=a.previous();h&&(d=h.getData("layoutId"));var c={cmd:"priority",doAsUserId:themeDisplay.getDoAsUserIdEncoded(),groupId:themeDisplay.getSiteGroupId(),layoutId:a.getData("layoutId"),nextLayoutId:c,p_auth:Liferay.authToken,previousLayoutId:d,privateLayout:themeDisplay.isPrivateLayout()},k=function(g){b._displayNotice(g.message);a.ancestor().insertBefore(a,
b._nextPageNode)},f=function(g){Liferay.fire("navigation",{item:a.getDOM(),type:"sort"})};e.io.request(b._updateURL,{data:c,dataType:"JSON",on:{failure:function(){k({message:'Your\x20request\x20failed\x20to\x20complete\x2e',status:p.BAD_REQUEST})},success:function(g,l,m){g=this.get("responseData");l=k;g.status===p.OK&&(l=f);l(g)}}})},["aui-io-request"],!0);Liferay.Navigation=q},"",{requires:["aui-component","event-mouseenter"]});
AUI.add("liferay-layout",function(e){var m=Liferay.Util,k=Liferay.Data.layoutConfig,c={EMPTY_COLUMNS:{},INITIALIZED:!1,OVER_NESTED_PORTLET:!1,PORTLET_TOPPER:e.Node.create('\x3cdiv class\x3d"portlet-topper"\x3e\x3c/div\x3e'),PROXY_NODE:e.Node.create('\x3cdiv class\x3d"lfr-portlet-proxy sortable-layout-proxy"\x3e\x3c/div\x3e'),PROXY_NODE_ITEM:e.Node.create('\x3cdiv class\x3d"lfr-portlet-proxy sortable-layout-proxy"\x3e\x3cdiv class\x3d"portlet-topper"\x3e\x3cspan class\x3d"portlet-title"\x3e\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e'),
options:k,bindDragDropListeners:function(){var a=c.getLayoutHandler();a.on("drag:end",e.bind("_onPortletDragEnd",c));a.on("drag:start",e.bind("_onPortletDragStart",c))},closeNestedPortlets:function(a){a.all(".portlet-boundary").each(function(b){Liferay.Portlet.close(b,!0,{nestedPortlet:!0})})},findIndex:function(a){var b=c.options;return a.get("parentNode").all("\x3e "+b.portletBoundary).indexOf(a)},findReferencePortlet:function(a){a=a.all("\x3e"+c.options.portletBoundary);var b=a.item(0),d=null;
if(b){var f=b.isStatic,g=null;f&&"end"!=f?a.each(function(l){var h=l.isStatic;if(!h||g&&h&&h!=g)d=l;g=h}):d=b}return d},fire:function(){var a=c.getLayoutHandler(),b;a&&(b=a.fire.apply(a,arguments));return b},getActiveDropContainer:function(){var a=c.options;return e.all(a.dropContainer+":not(."+a.disabledDropContainerClass+")").item(0)},getActiveDropNodes:function(){var a=c.options,b=[];e.all(a.dropContainer).each(function(d){d.hasClass(a.disabledDropContainerClass)||b.push(d.get("parentNode"))});
return e.all(b)},getLayoutHandler:function(){c.layoutHandler||Liferay.fire("initLayout");return c.layoutHandler},getPortlets:function(){return e.all(c.options.dragNodes)},hasMoved:function(a){var b=c.curPortletInfo,d=!1;if(b){var f=c.findIndex(a);a=a.get("parentNode");if(b.originalParent!=a||b.originalIndex!=f)d=!0}return d},hasPortlets:function(a){return!!a.one(c.options.portletBoundary)},on:function(){var a=c.getLayoutHandler(),b;a&&(b=a.on.apply(a,arguments));return b},refresh:function(a){var b=
c.getLayoutHandler();(a=e.one(a))&&b&&(b.delegate.syncTargets(),c.updatePortletDropZones(a))},saveIndex:function(a,b){var d=m.getColumnId(b.get("id")),f=m.getPortletId(a.get("id")),g=c.findIndex(a);c.hasMoved(a)&&(Liferay.fire("portletMoved",{portlet:a,portletId:f,position:g}),c.saveLayout({cmd:"move",p_p_col_id:d,p_p_col_pos:g,p_p_id:f}))},syncDraggableClassUI:function(){var a=c.options;if(a.dragNodes){var b=e.all(a.dragNodes);a.invalid&&(b=b.filter(":not("+a.invalid+")"));b.addClass("portlet-draggable")}},
syncEmptyColumnClassUI:function(a){var b=c.curPortletInfo,d=c.options;if(b){var f=c.hasPortlets(a),g=d.emptyColumnClass,b=b.originalParent,l=c.hasPortlets(b),h=a.ancestor(d.dropNodes),d=b.ancestor(d.dropNodes);h&&(h=h.get("id"),c.EMPTY_COLUMNS[h]=!f);d&&(d=d.get("id"),c.EMPTY_COLUMNS[d]=!l);a.toggleClass(g,!f);b.toggleClass(g,!l)}},updateCurrentPortletInfo:function(a){var b=c.options;c.curPortletInfo={node:a,originalIndex:c.findIndex(a),originalParent:a.get("parentNode"),siblingsPortlets:a.siblings(b.portletBoundary)}},
updateEmptyColumnsInfo:function(){e.all(c.options.dropNodes).each(function(a){var b=a.get("id");c.EMPTY_COLUMNS[b]=!c.hasPortlets(a)})},updatePortletDropZones:function(a){a=a.all(c.options.dropNodes);var b=c.getLayoutHandler();a.each(function(d){b.addDropNode(d)})},_afterPortletClose:function(a){(a=a.column)&&c.syncEmptyColumnClassUI(a)},_getPortletTitle:e.cached(function(a){var b=e.one("#"+a);a=b.one(".portlet-title");if(!a){a=c.PROXY_NODE_ITEM.one(".portlet-title");var b=b.one(".portlet-title-default"),
d="";b&&(d=b.html());a.html(d)}return a.outerHTML()}),_onPortletClose:function(a){var b=a.portlet,d=b.ancestor(c.options.dropContainer);c.updateCurrentPortletInfo(b);b.test(".portlet-nested-portlets")&&c.closeNestedPortlets(b);a.column=d},_onPortletDragEnd:function(a){a=a.target.get("node");var b=a.get("parentNode");c.saveIndex(a,b);c.syncEmptyColumnClassUI(b)},_onPortletDragStart:function(a){a=a.target.get("node");c.updateCurrentPortletInfo(a)},init:function(a){a=a||c.options;a.handles=e.Array(a.handles);
c.PROXY_NODE.append(c.PORTLET_TOPPER);var b=a.container;c._layoutContainer=e.one(b);c.DEFAULT_LAYOUT_OPTIONS={columnContainer:b,delegateConfig:{container:b,dragConfig:{clickPixelThresh:0,clickTimeThresh:250,plugins:[{cfg:{horizontal:!1,scrollDelay:30},fn:e.Plugin.DDWinScroll}]},handles:a.handles,invalid:a.invalid},dragNodes:a.dragNodes,dropContainer:function(d){return d.one(a.dropContainer)},dropNodes:c.getActiveDropNodes(),lazyStart:!0,proxy:{resizeFrame:!1}};b="liferay-layout-column";themeDisplay.isFreeformLayout()&&
(b="liferay-layout-freeform");e.use(b,function(){themeDisplay.isFreeformLayout()?c.FreeFormLayout.register():c.ColumnLayout.register();c.bindDragDropListeners();c.updateEmptyColumnsInfo();Liferay.after("closePortlet",c._afterPortletClose);Liferay.on("closePortlet",c._onPortletClose);Liferay.on("screenFlip",function(){c.getLayoutHandler().destroy()});c.INITIALIZED=!0})}};Liferay.provide(c,"saveLayout",function(a){var b={doAsUserId:themeDisplay.getDoAsUserIdEncoded(),p_auth:Liferay.authToken,p_l_id:themeDisplay.getPlid()};
e.mix(b,a);e.io.request(themeDisplay.getPathMain()+"/portal/update_layout",{after:{success:function(){Liferay.fire("updatedLayout")}},data:b})},["aui-io-request"]);Liferay.provide(c,"updateOverNestedPortletInfo",function(){var a=e.DD.DDM.activeDrop,b=c.options.nestedPortletId;a&&(a=a.get("node").get("id"),c.OVER_NESTED_PORTLET=-1<a.indexOf(b))},["dd-ddm"]);if(k&&(k=e.one(k.container),Liferay.once("initLayout",function(){c.init()}),k))if(e.UA.touch)Liferay.fire("initLayout");else k.once("mousemove",
function(){Liferay.fire("initLayout")});Liferay.Layout=c},"",{requires:[]});
